

#ifndef __COSE_Format_H
#define __COSE_Format_H

#include "krmllib.h"

#include "CBORDetAPI.h"
#include "CBORDetAbstract.h"

bool COSE_Format_validate_bool(cbor_det_t c);

typedef bool COSE_Format_vercdl_bool_pretty;

bool COSE_Format_uu___is_Mkvercdl_bool_pretty0(bool projectee);

/**
Parser for vercdl_bool
*/
bool COSE_Format_parse_bool(cbor_det_t c);

typedef struct Pulse_Lib_Slice_slice__uint8_t_s
{
  uint8_t *elt;
  size_t len;
}
Pulse_Lib_Slice_slice__uint8_t;

typedef enum { FStar_Pervasives_Native_None, FStar_Pervasives_Native_Some }
FStar_Pervasives_Native_option__size_t_tags;

/**
Serializer for vercdl_bool
*/
size_t COSE_Format_serialize_bool(bool c, Pulse_Lib_Slice_slice__uint8_t out);

typedef struct K___COSE_Format_vercdl_bool_pretty_Pulse_Lib_Slice_slice_uint8_t_s
{
  bool fst;
  Pulse_Lib_Slice_slice__uint8_t snd;
}
K___COSE_Format_vercdl_bool_pretty_Pulse_Lib_Slice_slice_uint8_t;

typedef struct
FStar_Pervasives_Native_option___COSE_Format_vercdl_bool_pretty___Pulse_Lib_Slice_slice_uint8_t__s
{
  FStar_Pervasives_Native_option__size_t_tags tag;
  K___COSE_Format_vercdl_bool_pretty_Pulse_Lib_Slice_slice_uint8_t v;
}
FStar_Pervasives_Native_option___COSE_Format_vercdl_bool_pretty___Pulse_Lib_Slice_slice_uint8_t_;

FStar_Pervasives_Native_option___COSE_Format_vercdl_bool_pretty___Pulse_Lib_Slice_slice_uint8_t_
COSE_Format_validate_and_parse_bool(Pulse_Lib_Slice_slice__uint8_t s);

bool COSE_Format_validate_separsenomatch(cbor_det_t c);

typedef enum { COSE_Format_Mkvercdl_separsenomatch_pretty0 }
COSE_Format_vercdl_separsenomatch_pretty;

bool
COSE_Format_uu___is_Mkvercdl_separsenomatch_pretty0(
  COSE_Format_vercdl_separsenomatch_pretty projectee
);

/**
Parser for vercdl_separsenomatch
*/
COSE_Format_vercdl_separsenomatch_pretty COSE_Format_parse_separsenomatch(cbor_det_t c);

/**
Serializer for vercdl_separsenomatch
*/
size_t
COSE_Format_serialize_separsenomatch(
  COSE_Format_vercdl_separsenomatch_pretty c,
  Pulse_Lib_Slice_slice__uint8_t out
);

typedef struct K___COSE_Format_vercdl_separsenomatch_pretty_Pulse_Lib_Slice_slice_uint8_t_s
{
  COSE_Format_vercdl_separsenomatch_pretty fst;
  Pulse_Lib_Slice_slice__uint8_t snd;
}
K___COSE_Format_vercdl_separsenomatch_pretty_Pulse_Lib_Slice_slice_uint8_t;

typedef struct
FStar_Pervasives_Native_option___COSE_Format_vercdl_separsenomatch_pretty___Pulse_Lib_Slice_slice_uint8_t__s
{
  FStar_Pervasives_Native_option__size_t_tags tag;
  K___COSE_Format_vercdl_separsenomatch_pretty_Pulse_Lib_Slice_slice_uint8_t v;
}
FStar_Pervasives_Native_option___COSE_Format_vercdl_separsenomatch_pretty___Pulse_Lib_Slice_slice_uint8_t_;

FStar_Pervasives_Native_option___COSE_Format_vercdl_separsenomatch_pretty___Pulse_Lib_Slice_slice_uint8_t_
COSE_Format_validate_and_parse_separsenomatch(Pulse_Lib_Slice_slice__uint8_t s);

bool COSE_Format_validate_uint(cbor_det_t c);

typedef uint64_t COSE_Format_vercdl_uint_pretty;

bool COSE_Format_uu___is_Mkvercdl_uint_pretty0(uint64_t projectee);

/**
Parser for vercdl_uint
*/
uint64_t COSE_Format_parse_uint(cbor_det_t c);

/**
Serializer for vercdl_uint
*/
size_t COSE_Format_serialize_uint(uint64_t c, Pulse_Lib_Slice_slice__uint8_t out);

typedef struct K___COSE_Format_vercdl_uint_pretty_Pulse_Lib_Slice_slice_uint8_t_s
{
  uint64_t fst;
  Pulse_Lib_Slice_slice__uint8_t snd;
}
K___COSE_Format_vercdl_uint_pretty_Pulse_Lib_Slice_slice_uint8_t;

typedef struct
FStar_Pervasives_Native_option___COSE_Format_vercdl_uint_pretty___Pulse_Lib_Slice_slice_uint8_t__s
{
  FStar_Pervasives_Native_option__size_t_tags tag;
  K___COSE_Format_vercdl_uint_pretty_Pulse_Lib_Slice_slice_uint8_t v;
}
FStar_Pervasives_Native_option___COSE_Format_vercdl_uint_pretty___Pulse_Lib_Slice_slice_uint8_t_;

FStar_Pervasives_Native_option___COSE_Format_vercdl_uint_pretty___Pulse_Lib_Slice_slice_uint8_t_
COSE_Format_validate_and_parse_uint(Pulse_Lib_Slice_slice__uint8_t s);

bool COSE_Format_validate_nint(cbor_det_t c);

typedef uint64_t COSE_Format_vercdl_nint_pretty;

bool COSE_Format_uu___is_Mkvercdl_nint_pretty0(uint64_t projectee);

/**
Parser for vercdl_nint
*/
uint64_t COSE_Format_parse_nint(cbor_det_t c);

/**
Serializer for vercdl_nint
*/
size_t COSE_Format_serialize_nint(uint64_t c, Pulse_Lib_Slice_slice__uint8_t out);

typedef struct K___COSE_Format_vercdl_nint_pretty_Pulse_Lib_Slice_slice_uint8_t_s
{
  uint64_t fst;
  Pulse_Lib_Slice_slice__uint8_t snd;
}
K___COSE_Format_vercdl_nint_pretty_Pulse_Lib_Slice_slice_uint8_t;

typedef struct
FStar_Pervasives_Native_option___COSE_Format_vercdl_nint_pretty___Pulse_Lib_Slice_slice_uint8_t__s
{
  FStar_Pervasives_Native_option__size_t_tags tag;
  K___COSE_Format_vercdl_nint_pretty_Pulse_Lib_Slice_slice_uint8_t v;
}
FStar_Pervasives_Native_option___COSE_Format_vercdl_nint_pretty___Pulse_Lib_Slice_slice_uint8_t_;

FStar_Pervasives_Native_option___COSE_Format_vercdl_nint_pretty___Pulse_Lib_Slice_slice_uint8_t_
COSE_Format_validate_and_parse_nint(Pulse_Lib_Slice_slice__uint8_t s);

bool COSE_Format_validate_int(cbor_det_t c);

typedef enum { COSE_Format_Inl, COSE_Format_Inr } COSE_Format_vercdl_int_tags;

typedef enum { COSE_Format_Mkvercdl_int_pretty0, COSE_Format_Mkvercdl_int_pretty1 }
COSE_Format_vercdl_int_pretty_tags;

typedef struct COSE_Format_vercdl_int_pretty_s
{
  COSE_Format_vercdl_int_pretty_tags tag;
  union {
    uint64_t case_Mkvercdl_int_pretty0;
    uint64_t case_Mkvercdl_int_pretty1;
  }
  ;
}
COSE_Format_vercdl_int_pretty;

bool COSE_Format_uu___is_Mkvercdl_int_pretty0(COSE_Format_vercdl_int_pretty projectee);

bool COSE_Format_uu___is_Mkvercdl_int_pretty1(COSE_Format_vercdl_int_pretty projectee);

/**
Parser for vercdl_int
*/
COSE_Format_vercdl_int_pretty COSE_Format_parse_int(cbor_det_t c);

/**
Serializer for vercdl_int
*/
size_t
COSE_Format_serialize_int(
  COSE_Format_vercdl_int_pretty c,
  Pulse_Lib_Slice_slice__uint8_t out
);

typedef struct K___COSE_Format_vercdl_int_pretty_Pulse_Lib_Slice_slice_uint8_t_s
{
  COSE_Format_vercdl_int_pretty fst;
  Pulse_Lib_Slice_slice__uint8_t snd;
}
K___COSE_Format_vercdl_int_pretty_Pulse_Lib_Slice_slice_uint8_t;

typedef struct
FStar_Pervasives_Native_option___COSE_Format_vercdl_int_pretty___Pulse_Lib_Slice_slice_uint8_t__s
{
  FStar_Pervasives_Native_option__size_t_tags tag;
  K___COSE_Format_vercdl_int_pretty_Pulse_Lib_Slice_slice_uint8_t v;
}
FStar_Pervasives_Native_option___COSE_Format_vercdl_int_pretty___Pulse_Lib_Slice_slice_uint8_t_;

FStar_Pervasives_Native_option___COSE_Format_vercdl_int_pretty___Pulse_Lib_Slice_slice_uint8_t_
COSE_Format_validate_and_parse_int(Pulse_Lib_Slice_slice__uint8_t s);

bool COSE_Format_validate_bstr(cbor_det_t c);

typedef Pulse_Lib_Slice_slice__uint8_t COSE_Format_vercdl_bstr;

typedef COSE_Format_vercdl_bstr COSE_Format_vercdl_bstr_pretty;

bool COSE_Format_uu___is_Mkvercdl_bstr_pretty0(COSE_Format_vercdl_bstr projectee);

/**
Parser for vercdl_bstr
*/
COSE_Format_vercdl_bstr COSE_Format_parse_bstr(cbor_det_t c);

/**
Serializer for vercdl_bstr
*/
size_t
COSE_Format_serialize_bstr(COSE_Format_vercdl_bstr c, Pulse_Lib_Slice_slice__uint8_t out);

typedef struct K___COSE_Format_vercdl_bstr_pretty_Pulse_Lib_Slice_slice_uint8_t_s
{
  COSE_Format_vercdl_bstr fst;
  Pulse_Lib_Slice_slice__uint8_t snd;
}
K___COSE_Format_vercdl_bstr_pretty_Pulse_Lib_Slice_slice_uint8_t;

typedef struct
FStar_Pervasives_Native_option___COSE_Format_vercdl_bstr_pretty___Pulse_Lib_Slice_slice_uint8_t__s
{
  FStar_Pervasives_Native_option__size_t_tags tag;
  K___COSE_Format_vercdl_bstr_pretty_Pulse_Lib_Slice_slice_uint8_t v;
}
FStar_Pervasives_Native_option___COSE_Format_vercdl_bstr_pretty___Pulse_Lib_Slice_slice_uint8_t_;

FStar_Pervasives_Native_option___COSE_Format_vercdl_bstr_pretty___Pulse_Lib_Slice_slice_uint8_t_
COSE_Format_validate_and_parse_bstr(Pulse_Lib_Slice_slice__uint8_t s);

bool COSE_Format_validate_encodedcbor(cbor_det_t c);

typedef COSE_Format_vercdl_bstr_pretty COSE_Format_vercdl_encodedcbor_pretty;

bool
COSE_Format_uu___is_Mkvercdl_encodedcbor_pretty0(COSE_Format_vercdl_bstr_pretty projectee);

/**
Parser for vercdl_encodedcbor
*/
COSE_Format_vercdl_bstr_pretty COSE_Format_parse_encodedcbor(cbor_det_t c);

/**
Serializer for vercdl_encodedcbor
*/
size_t
COSE_Format_serialize_encodedcbor(
  COSE_Format_vercdl_bstr_pretty c,
  Pulse_Lib_Slice_slice__uint8_t out
);

typedef struct K___COSE_Format_vercdl_encodedcbor_pretty_Pulse_Lib_Slice_slice_uint8_t_s
{
  COSE_Format_vercdl_bstr_pretty fst;
  Pulse_Lib_Slice_slice__uint8_t snd;
}
K___COSE_Format_vercdl_encodedcbor_pretty_Pulse_Lib_Slice_slice_uint8_t;

typedef struct
FStar_Pervasives_Native_option___COSE_Format_vercdl_encodedcbor_pretty___Pulse_Lib_Slice_slice_uint8_t__s
{
  FStar_Pervasives_Native_option__size_t_tags tag;
  K___COSE_Format_vercdl_encodedcbor_pretty_Pulse_Lib_Slice_slice_uint8_t v;
}
FStar_Pervasives_Native_option___COSE_Format_vercdl_encodedcbor_pretty___Pulse_Lib_Slice_slice_uint8_t_;

FStar_Pervasives_Native_option___COSE_Format_vercdl_encodedcbor_pretty___Pulse_Lib_Slice_slice_uint8_t_
COSE_Format_validate_and_parse_encodedcbor(Pulse_Lib_Slice_slice__uint8_t s);

bool COSE_Format_validate_bytes(cbor_det_t c);

typedef COSE_Format_vercdl_bstr_pretty COSE_Format_vercdl_bytes_pretty;

bool COSE_Format_uu___is_Mkvercdl_bytes_pretty0(COSE_Format_vercdl_bstr_pretty projectee);

/**
Parser for vercdl_bytes
*/
COSE_Format_vercdl_bstr_pretty COSE_Format_parse_bytes(cbor_det_t c);

/**
Serializer for vercdl_bytes
*/
size_t
COSE_Format_serialize_bytes(
  COSE_Format_vercdl_bstr_pretty c,
  Pulse_Lib_Slice_slice__uint8_t out
);

typedef struct K___COSE_Format_vercdl_bytes_pretty_Pulse_Lib_Slice_slice_uint8_t_s
{
  COSE_Format_vercdl_bstr_pretty fst;
  Pulse_Lib_Slice_slice__uint8_t snd;
}
K___COSE_Format_vercdl_bytes_pretty_Pulse_Lib_Slice_slice_uint8_t;

typedef struct
FStar_Pervasives_Native_option___COSE_Format_vercdl_bytes_pretty___Pulse_Lib_Slice_slice_uint8_t__s
{
  FStar_Pervasives_Native_option__size_t_tags tag;
  K___COSE_Format_vercdl_bytes_pretty_Pulse_Lib_Slice_slice_uint8_t v;
}
FStar_Pervasives_Native_option___COSE_Format_vercdl_bytes_pretty___Pulse_Lib_Slice_slice_uint8_t_;

FStar_Pervasives_Native_option___COSE_Format_vercdl_bytes_pretty___Pulse_Lib_Slice_slice_uint8_t_
COSE_Format_validate_and_parse_bytes(Pulse_Lib_Slice_slice__uint8_t s);

bool COSE_Format_validate_tstr(cbor_det_t c);

typedef COSE_Format_vercdl_bstr COSE_Format_vercdl_tstr_pretty;

bool COSE_Format_uu___is_Mkvercdl_tstr_pretty0(COSE_Format_vercdl_bstr projectee);

/**
Parser for vercdl_tstr
*/
COSE_Format_vercdl_bstr COSE_Format_parse_tstr(cbor_det_t c);

/**
Serializer for vercdl_tstr
*/
size_t
COSE_Format_serialize_tstr(COSE_Format_vercdl_bstr c, Pulse_Lib_Slice_slice__uint8_t out);

typedef struct K___COSE_Format_vercdl_tstr_pretty_Pulse_Lib_Slice_slice_uint8_t_s
{
  COSE_Format_vercdl_bstr fst;
  Pulse_Lib_Slice_slice__uint8_t snd;
}
K___COSE_Format_vercdl_tstr_pretty_Pulse_Lib_Slice_slice_uint8_t;

typedef struct
FStar_Pervasives_Native_option___COSE_Format_vercdl_tstr_pretty___Pulse_Lib_Slice_slice_uint8_t__s
{
  FStar_Pervasives_Native_option__size_t_tags tag;
  K___COSE_Format_vercdl_tstr_pretty_Pulse_Lib_Slice_slice_uint8_t v;
}
FStar_Pervasives_Native_option___COSE_Format_vercdl_tstr_pretty___Pulse_Lib_Slice_slice_uint8_t_;

FStar_Pervasives_Native_option___COSE_Format_vercdl_tstr_pretty___Pulse_Lib_Slice_slice_uint8_t_
COSE_Format_validate_and_parse_tstr(Pulse_Lib_Slice_slice__uint8_t s);

bool COSE_Format_validate_label(cbor_det_t c);

typedef struct COSE_Format_vercdl_label_s
{
  COSE_Format_vercdl_int_tags tag;
  union {
    COSE_Format_vercdl_int_pretty case_Inl;
    COSE_Format_vercdl_bstr case_Inr;
  }
  ;
}
COSE_Format_vercdl_label;

typedef enum { COSE_Format_Mkvercdl_label_pretty0, COSE_Format_Mkvercdl_label_pretty1 }
COSE_Format_vercdl_label_pretty_tags;

typedef struct COSE_Format_vercdl_label_pretty_s
{
  COSE_Format_vercdl_label_pretty_tags tag;
  union {
    COSE_Format_vercdl_int_pretty case_Mkvercdl_label_pretty0;
    COSE_Format_vercdl_bstr case_Mkvercdl_label_pretty1;
  }
  ;
}
COSE_Format_vercdl_label_pretty;

bool COSE_Format_uu___is_Mkvercdl_label_pretty0(COSE_Format_vercdl_label_pretty projectee);

bool COSE_Format_uu___is_Mkvercdl_label_pretty1(COSE_Format_vercdl_label_pretty projectee);

/**
Parser for vercdl_label
*/
COSE_Format_vercdl_label_pretty COSE_Format_parse_label(cbor_det_t c);

/**
Serializer for vercdl_label
*/
size_t
COSE_Format_serialize_label(
  COSE_Format_vercdl_label_pretty c,
  Pulse_Lib_Slice_slice__uint8_t out
);

typedef struct K___COSE_Format_vercdl_label_pretty_Pulse_Lib_Slice_slice_uint8_t_s
{
  COSE_Format_vercdl_label_pretty fst;
  Pulse_Lib_Slice_slice__uint8_t snd;
}
K___COSE_Format_vercdl_label_pretty_Pulse_Lib_Slice_slice_uint8_t;

typedef struct
FStar_Pervasives_Native_option___COSE_Format_vercdl_label_pretty___Pulse_Lib_Slice_slice_uint8_t__s
{
  FStar_Pervasives_Native_option__size_t_tags tag;
  K___COSE_Format_vercdl_label_pretty_Pulse_Lib_Slice_slice_uint8_t v;
}
FStar_Pervasives_Native_option___COSE_Format_vercdl_label_pretty___Pulse_Lib_Slice_slice_uint8_t_;

FStar_Pervasives_Native_option___COSE_Format_vercdl_label_pretty___Pulse_Lib_Slice_slice_uint8_t_
COSE_Format_validate_and_parse_label(Pulse_Lib_Slice_slice__uint8_t s);

bool COSE_Format_validate_tdate(cbor_det_t c);

typedef COSE_Format_vercdl_tstr_pretty COSE_Format_vercdl_tdate_pretty;

bool COSE_Format_uu___is_Mkvercdl_tdate_pretty0(COSE_Format_vercdl_tstr_pretty projectee);

/**
Parser for vercdl_tdate
*/
COSE_Format_vercdl_tstr_pretty COSE_Format_parse_tdate(cbor_det_t c);

/**
Serializer for vercdl_tdate
*/
size_t
COSE_Format_serialize_tdate(
  COSE_Format_vercdl_tstr_pretty c,
  Pulse_Lib_Slice_slice__uint8_t out
);

typedef struct K___COSE_Format_vercdl_tdate_pretty_Pulse_Lib_Slice_slice_uint8_t_s
{
  COSE_Format_vercdl_tstr_pretty fst;
  Pulse_Lib_Slice_slice__uint8_t snd;
}
K___COSE_Format_vercdl_tdate_pretty_Pulse_Lib_Slice_slice_uint8_t;

typedef struct
FStar_Pervasives_Native_option___COSE_Format_vercdl_tdate_pretty___Pulse_Lib_Slice_slice_uint8_t__s
{
  FStar_Pervasives_Native_option__size_t_tags tag;
  K___COSE_Format_vercdl_tdate_pretty_Pulse_Lib_Slice_slice_uint8_t v;
}
FStar_Pervasives_Native_option___COSE_Format_vercdl_tdate_pretty___Pulse_Lib_Slice_slice_uint8_t_;

FStar_Pervasives_Native_option___COSE_Format_vercdl_tdate_pretty___Pulse_Lib_Slice_slice_uint8_t_
COSE_Format_validate_and_parse_tdate(Pulse_Lib_Slice_slice__uint8_t s);

bool COSE_Format_validate_uri(cbor_det_t c);

typedef COSE_Format_vercdl_tstr_pretty COSE_Format_vercdl_uri_pretty;

bool COSE_Format_uu___is_Mkvercdl_uri_pretty0(COSE_Format_vercdl_tstr_pretty projectee);

/**
Parser for vercdl_uri
*/
COSE_Format_vercdl_tstr_pretty COSE_Format_parse_uri(cbor_det_t c);

/**
Serializer for vercdl_uri
*/
size_t
COSE_Format_serialize_uri(
  COSE_Format_vercdl_tstr_pretty c,
  Pulse_Lib_Slice_slice__uint8_t out
);

typedef struct K___COSE_Format_vercdl_uri_pretty_Pulse_Lib_Slice_slice_uint8_t_s
{
  COSE_Format_vercdl_tstr_pretty fst;
  Pulse_Lib_Slice_slice__uint8_t snd;
}
K___COSE_Format_vercdl_uri_pretty_Pulse_Lib_Slice_slice_uint8_t;

typedef struct
FStar_Pervasives_Native_option___COSE_Format_vercdl_uri_pretty___Pulse_Lib_Slice_slice_uint8_t__s
{
  FStar_Pervasives_Native_option__size_t_tags tag;
  K___COSE_Format_vercdl_uri_pretty_Pulse_Lib_Slice_slice_uint8_t v;
}
FStar_Pervasives_Native_option___COSE_Format_vercdl_uri_pretty___Pulse_Lib_Slice_slice_uint8_t_;

FStar_Pervasives_Native_option___COSE_Format_vercdl_uri_pretty___Pulse_Lib_Slice_slice_uint8_t_
COSE_Format_validate_and_parse_uri(Pulse_Lib_Slice_slice__uint8_t s);

bool COSE_Format_validate_b64url(cbor_det_t c);

typedef COSE_Format_vercdl_tstr_pretty COSE_Format_vercdl_b64url_pretty;

bool COSE_Format_uu___is_Mkvercdl_b64url_pretty0(COSE_Format_vercdl_tstr_pretty projectee);

/**
Parser for vercdl_b64url
*/
COSE_Format_vercdl_tstr_pretty COSE_Format_parse_b64url(cbor_det_t c);

/**
Serializer for vercdl_b64url
*/
size_t
COSE_Format_serialize_b64url(
  COSE_Format_vercdl_tstr_pretty c,
  Pulse_Lib_Slice_slice__uint8_t out
);

typedef struct K___COSE_Format_vercdl_b64url_pretty_Pulse_Lib_Slice_slice_uint8_t_s
{
  COSE_Format_vercdl_tstr_pretty fst;
  Pulse_Lib_Slice_slice__uint8_t snd;
}
K___COSE_Format_vercdl_b64url_pretty_Pulse_Lib_Slice_slice_uint8_t;

typedef struct
FStar_Pervasives_Native_option___COSE_Format_vercdl_b64url_pretty___Pulse_Lib_Slice_slice_uint8_t__s
{
  FStar_Pervasives_Native_option__size_t_tags tag;
  K___COSE_Format_vercdl_b64url_pretty_Pulse_Lib_Slice_slice_uint8_t v;
}
FStar_Pervasives_Native_option___COSE_Format_vercdl_b64url_pretty___Pulse_Lib_Slice_slice_uint8_t_;

FStar_Pervasives_Native_option___COSE_Format_vercdl_b64url_pretty___Pulse_Lib_Slice_slice_uint8_t_
COSE_Format_validate_and_parse_b64url(Pulse_Lib_Slice_slice__uint8_t s);

bool COSE_Format_validate_b64legacy(cbor_det_t c);

typedef COSE_Format_vercdl_tstr_pretty COSE_Format_vercdl_b64legacy_pretty;

bool
COSE_Format_uu___is_Mkvercdl_b64legacy_pretty0(COSE_Format_vercdl_tstr_pretty projectee);

/**
Parser for vercdl_b64legacy
*/
COSE_Format_vercdl_tstr_pretty COSE_Format_parse_b64legacy(cbor_det_t c);

/**
Serializer for vercdl_b64legacy
*/
size_t
COSE_Format_serialize_b64legacy(
  COSE_Format_vercdl_tstr_pretty c,
  Pulse_Lib_Slice_slice__uint8_t out
);

typedef struct K___COSE_Format_vercdl_b64legacy_pretty_Pulse_Lib_Slice_slice_uint8_t_s
{
  COSE_Format_vercdl_tstr_pretty fst;
  Pulse_Lib_Slice_slice__uint8_t snd;
}
K___COSE_Format_vercdl_b64legacy_pretty_Pulse_Lib_Slice_slice_uint8_t;

typedef struct
FStar_Pervasives_Native_option___COSE_Format_vercdl_b64legacy_pretty___Pulse_Lib_Slice_slice_uint8_t__s
{
  FStar_Pervasives_Native_option__size_t_tags tag;
  K___COSE_Format_vercdl_b64legacy_pretty_Pulse_Lib_Slice_slice_uint8_t v;
}
FStar_Pervasives_Native_option___COSE_Format_vercdl_b64legacy_pretty___Pulse_Lib_Slice_slice_uint8_t_;

FStar_Pervasives_Native_option___COSE_Format_vercdl_b64legacy_pretty___Pulse_Lib_Slice_slice_uint8_t_
COSE_Format_validate_and_parse_b64legacy(Pulse_Lib_Slice_slice__uint8_t s);

bool COSE_Format_validate_regexp(cbor_det_t c);

typedef COSE_Format_vercdl_tstr_pretty COSE_Format_vercdl_regexp_pretty;

bool COSE_Format_uu___is_Mkvercdl_regexp_pretty0(COSE_Format_vercdl_tstr_pretty projectee);

/**
Parser for vercdl_regexp
*/
COSE_Format_vercdl_tstr_pretty COSE_Format_parse_regexp(cbor_det_t c);

/**
Serializer for vercdl_regexp
*/
size_t
COSE_Format_serialize_regexp(
  COSE_Format_vercdl_tstr_pretty c,
  Pulse_Lib_Slice_slice__uint8_t out
);

typedef struct K___COSE_Format_vercdl_regexp_pretty_Pulse_Lib_Slice_slice_uint8_t_s
{
  COSE_Format_vercdl_tstr_pretty fst;
  Pulse_Lib_Slice_slice__uint8_t snd;
}
K___COSE_Format_vercdl_regexp_pretty_Pulse_Lib_Slice_slice_uint8_t;

typedef struct
FStar_Pervasives_Native_option___COSE_Format_vercdl_regexp_pretty___Pulse_Lib_Slice_slice_uint8_t__s
{
  FStar_Pervasives_Native_option__size_t_tags tag;
  K___COSE_Format_vercdl_regexp_pretty_Pulse_Lib_Slice_slice_uint8_t v;
}
FStar_Pervasives_Native_option___COSE_Format_vercdl_regexp_pretty___Pulse_Lib_Slice_slice_uint8_t_;

FStar_Pervasives_Native_option___COSE_Format_vercdl_regexp_pretty___Pulse_Lib_Slice_slice_uint8_t_
COSE_Format_validate_and_parse_regexp(Pulse_Lib_Slice_slice__uint8_t s);

bool COSE_Format_validate_mimemessage(cbor_det_t c);

typedef COSE_Format_vercdl_tstr_pretty COSE_Format_vercdl_mimemessage_pretty;

bool
COSE_Format_uu___is_Mkvercdl_mimemessage_pretty0(COSE_Format_vercdl_tstr_pretty projectee);

/**
Parser for vercdl_mimemessage
*/
COSE_Format_vercdl_tstr_pretty COSE_Format_parse_mimemessage(cbor_det_t c);

/**
Serializer for vercdl_mimemessage
*/
size_t
COSE_Format_serialize_mimemessage(
  COSE_Format_vercdl_tstr_pretty c,
  Pulse_Lib_Slice_slice__uint8_t out
);

typedef struct K___COSE_Format_vercdl_mimemessage_pretty_Pulse_Lib_Slice_slice_uint8_t_s
{
  COSE_Format_vercdl_tstr_pretty fst;
  Pulse_Lib_Slice_slice__uint8_t snd;
}
K___COSE_Format_vercdl_mimemessage_pretty_Pulse_Lib_Slice_slice_uint8_t;

typedef struct
FStar_Pervasives_Native_option___COSE_Format_vercdl_mimemessage_pretty___Pulse_Lib_Slice_slice_uint8_t__s
{
  FStar_Pervasives_Native_option__size_t_tags tag;
  K___COSE_Format_vercdl_mimemessage_pretty_Pulse_Lib_Slice_slice_uint8_t v;
}
FStar_Pervasives_Native_option___COSE_Format_vercdl_mimemessage_pretty___Pulse_Lib_Slice_slice_uint8_t_;

FStar_Pervasives_Native_option___COSE_Format_vercdl_mimemessage_pretty___Pulse_Lib_Slice_slice_uint8_t_
COSE_Format_validate_and_parse_mimemessage(Pulse_Lib_Slice_slice__uint8_t s);

bool COSE_Format_validate_text(cbor_det_t c);

typedef COSE_Format_vercdl_tstr_pretty COSE_Format_vercdl_text_pretty;

bool COSE_Format_uu___is_Mkvercdl_text_pretty0(COSE_Format_vercdl_tstr_pretty projectee);

/**
Parser for vercdl_text
*/
COSE_Format_vercdl_tstr_pretty COSE_Format_parse_text(cbor_det_t c);

/**
Serializer for vercdl_text
*/
size_t
COSE_Format_serialize_text(
  COSE_Format_vercdl_tstr_pretty c,
  Pulse_Lib_Slice_slice__uint8_t out
);

typedef struct K___COSE_Format_vercdl_text_pretty_Pulse_Lib_Slice_slice_uint8_t_s
{
  COSE_Format_vercdl_tstr_pretty fst;
  Pulse_Lib_Slice_slice__uint8_t snd;
}
K___COSE_Format_vercdl_text_pretty_Pulse_Lib_Slice_slice_uint8_t;

typedef struct
FStar_Pervasives_Native_option___COSE_Format_vercdl_text_pretty___Pulse_Lib_Slice_slice_uint8_t__s
{
  FStar_Pervasives_Native_option__size_t_tags tag;
  K___COSE_Format_vercdl_text_pretty_Pulse_Lib_Slice_slice_uint8_t v;
}
FStar_Pervasives_Native_option___COSE_Format_vercdl_text_pretty___Pulse_Lib_Slice_slice_uint8_t_;

FStar_Pervasives_Native_option___COSE_Format_vercdl_text_pretty___Pulse_Lib_Slice_slice_uint8_t_
COSE_Format_validate_and_parse_text(Pulse_Lib_Slice_slice__uint8_t s);

bool COSE_Format_validate_false(cbor_det_t c);

typedef enum { COSE_Format_Mkvercdl_false_pretty0 } COSE_Format_vercdl_false_pretty;

bool COSE_Format_uu___is_Mkvercdl_false_pretty0(COSE_Format_vercdl_false_pretty projectee);

/**
Parser for vercdl_false
*/
COSE_Format_vercdl_false_pretty COSE_Format_parse_false(cbor_det_t c);

/**
Serializer for vercdl_false
*/
size_t
COSE_Format_serialize_false(
  COSE_Format_vercdl_false_pretty c,
  Pulse_Lib_Slice_slice__uint8_t out
);

typedef struct K___COSE_Format_vercdl_false_pretty_Pulse_Lib_Slice_slice_uint8_t_s
{
  COSE_Format_vercdl_false_pretty fst;
  Pulse_Lib_Slice_slice__uint8_t snd;
}
K___COSE_Format_vercdl_false_pretty_Pulse_Lib_Slice_slice_uint8_t;

typedef struct
FStar_Pervasives_Native_option___COSE_Format_vercdl_false_pretty___Pulse_Lib_Slice_slice_uint8_t__s
{
  FStar_Pervasives_Native_option__size_t_tags tag;
  K___COSE_Format_vercdl_false_pretty_Pulse_Lib_Slice_slice_uint8_t v;
}
FStar_Pervasives_Native_option___COSE_Format_vercdl_false_pretty___Pulse_Lib_Slice_slice_uint8_t_;

FStar_Pervasives_Native_option___COSE_Format_vercdl_false_pretty___Pulse_Lib_Slice_slice_uint8_t_
COSE_Format_validate_and_parse_false(Pulse_Lib_Slice_slice__uint8_t s);

bool COSE_Format_validate_true(cbor_det_t c);

typedef enum { COSE_Format_Mkvercdl_true_pretty0 } COSE_Format_vercdl_true_pretty;

bool COSE_Format_uu___is_Mkvercdl_true_pretty0(COSE_Format_vercdl_true_pretty projectee);

/**
Parser for vercdl_true
*/
COSE_Format_vercdl_true_pretty COSE_Format_parse_true(cbor_det_t c);

/**
Serializer for vercdl_true
*/
size_t
COSE_Format_serialize_true(
  COSE_Format_vercdl_true_pretty c,
  Pulse_Lib_Slice_slice__uint8_t out
);

typedef struct K___COSE_Format_vercdl_true_pretty_Pulse_Lib_Slice_slice_uint8_t_s
{
  COSE_Format_vercdl_true_pretty fst;
  Pulse_Lib_Slice_slice__uint8_t snd;
}
K___COSE_Format_vercdl_true_pretty_Pulse_Lib_Slice_slice_uint8_t;

typedef struct
FStar_Pervasives_Native_option___COSE_Format_vercdl_true_pretty___Pulse_Lib_Slice_slice_uint8_t__s
{
  FStar_Pervasives_Native_option__size_t_tags tag;
  K___COSE_Format_vercdl_true_pretty_Pulse_Lib_Slice_slice_uint8_t v;
}
FStar_Pervasives_Native_option___COSE_Format_vercdl_true_pretty___Pulse_Lib_Slice_slice_uint8_t_;

FStar_Pervasives_Native_option___COSE_Format_vercdl_true_pretty___Pulse_Lib_Slice_slice_uint8_t_
COSE_Format_validate_and_parse_true(Pulse_Lib_Slice_slice__uint8_t s);

bool COSE_Format_validate_nil(cbor_det_t c);

typedef enum { COSE_Format_Mkvercdl_nil_pretty0 } COSE_Format_vercdl_nil_pretty;

bool COSE_Format_uu___is_Mkvercdl_nil_pretty0(COSE_Format_vercdl_nil_pretty projectee);

/**
Parser for vercdl_nil
*/
COSE_Format_vercdl_nil_pretty COSE_Format_parse_nil(cbor_det_t c);

/**
Serializer for vercdl_nil
*/
size_t
COSE_Format_serialize_nil(
  COSE_Format_vercdl_nil_pretty c,
  Pulse_Lib_Slice_slice__uint8_t out
);

typedef struct K___COSE_Format_vercdl_nil_pretty_Pulse_Lib_Slice_slice_uint8_t_s
{
  COSE_Format_vercdl_nil_pretty fst;
  Pulse_Lib_Slice_slice__uint8_t snd;
}
K___COSE_Format_vercdl_nil_pretty_Pulse_Lib_Slice_slice_uint8_t;

typedef struct
FStar_Pervasives_Native_option___COSE_Format_vercdl_nil_pretty___Pulse_Lib_Slice_slice_uint8_t__s
{
  FStar_Pervasives_Native_option__size_t_tags tag;
  K___COSE_Format_vercdl_nil_pretty_Pulse_Lib_Slice_slice_uint8_t v;
}
FStar_Pervasives_Native_option___COSE_Format_vercdl_nil_pretty___Pulse_Lib_Slice_slice_uint8_t_;

FStar_Pervasives_Native_option___COSE_Format_vercdl_nil_pretty___Pulse_Lib_Slice_slice_uint8_t_
COSE_Format_validate_and_parse_nil(Pulse_Lib_Slice_slice__uint8_t s);

bool COSE_Format_validate_null(cbor_det_t c);

typedef COSE_Format_vercdl_nil_pretty COSE_Format_vercdl_null_pretty;

bool COSE_Format_uu___is_Mkvercdl_null_pretty0(COSE_Format_vercdl_nil_pretty projectee);

/**
Parser for vercdl_null
*/
COSE_Format_vercdl_nil_pretty COSE_Format_parse_null(cbor_det_t c);

/**
Serializer for vercdl_null
*/
size_t
COSE_Format_serialize_null(
  COSE_Format_vercdl_nil_pretty c,
  Pulse_Lib_Slice_slice__uint8_t out
);

typedef struct K___COSE_Format_vercdl_null_pretty_Pulse_Lib_Slice_slice_uint8_t_s
{
  COSE_Format_vercdl_nil_pretty fst;
  Pulse_Lib_Slice_slice__uint8_t snd;
}
K___COSE_Format_vercdl_null_pretty_Pulse_Lib_Slice_slice_uint8_t;

typedef struct
FStar_Pervasives_Native_option___COSE_Format_vercdl_null_pretty___Pulse_Lib_Slice_slice_uint8_t__s
{
  FStar_Pervasives_Native_option__size_t_tags tag;
  K___COSE_Format_vercdl_null_pretty_Pulse_Lib_Slice_slice_uint8_t v;
}
FStar_Pervasives_Native_option___COSE_Format_vercdl_null_pretty___Pulse_Lib_Slice_slice_uint8_t_;

FStar_Pervasives_Native_option___COSE_Format_vercdl_null_pretty___Pulse_Lib_Slice_slice_uint8_t_
COSE_Format_validate_and_parse_null(Pulse_Lib_Slice_slice__uint8_t s);

bool COSE_Format_validate_undefined(cbor_det_t c);

typedef enum { COSE_Format_Mkvercdl_undefined_pretty0 }
COSE_Format_vercdl_undefined_pretty;

bool
COSE_Format_uu___is_Mkvercdl_undefined_pretty0(
  COSE_Format_vercdl_undefined_pretty projectee
);

/**
Parser for vercdl_undefined
*/
COSE_Format_vercdl_undefined_pretty COSE_Format_parse_undefined(cbor_det_t c);

/**
Serializer for vercdl_undefined
*/
size_t
COSE_Format_serialize_undefined(
  COSE_Format_vercdl_undefined_pretty c,
  Pulse_Lib_Slice_slice__uint8_t out
);

typedef struct K___COSE_Format_vercdl_undefined_pretty_Pulse_Lib_Slice_slice_uint8_t_s
{
  COSE_Format_vercdl_undefined_pretty fst;
  Pulse_Lib_Slice_slice__uint8_t snd;
}
K___COSE_Format_vercdl_undefined_pretty_Pulse_Lib_Slice_slice_uint8_t;

typedef struct
FStar_Pervasives_Native_option___COSE_Format_vercdl_undefined_pretty___Pulse_Lib_Slice_slice_uint8_t__s
{
  FStar_Pervasives_Native_option__size_t_tags tag;
  K___COSE_Format_vercdl_undefined_pretty_Pulse_Lib_Slice_slice_uint8_t v;
}
FStar_Pervasives_Native_option___COSE_Format_vercdl_undefined_pretty___Pulse_Lib_Slice_slice_uint8_t_;

FStar_Pervasives_Native_option___COSE_Format_vercdl_undefined_pretty___Pulse_Lib_Slice_slice_uint8_t_
COSE_Format_validate_and_parse_undefined(Pulse_Lib_Slice_slice__uint8_t s);

bool COSE_Format_validate_any(cbor_det_t c);

typedef cbor_det_t COSE_Format_vercdl_any;

typedef COSE_Format_vercdl_any COSE_Format_vercdl_any_pretty;

bool COSE_Format_uu___is_Mkvercdl_any_pretty0(COSE_Format_vercdl_any projectee);

/**
Parser for vercdl_any
*/
COSE_Format_vercdl_any COSE_Format_parse_any(cbor_det_t c);

/**
Serializer for vercdl_any
*/
size_t
COSE_Format_serialize_any(COSE_Format_vercdl_any c, Pulse_Lib_Slice_slice__uint8_t out);

typedef struct K___COSE_Format_vercdl_any_pretty_Pulse_Lib_Slice_slice_uint8_t_s
{
  COSE_Format_vercdl_any fst;
  Pulse_Lib_Slice_slice__uint8_t snd;
}
K___COSE_Format_vercdl_any_pretty_Pulse_Lib_Slice_slice_uint8_t;

typedef struct
FStar_Pervasives_Native_option___COSE_Format_vercdl_any_pretty___Pulse_Lib_Slice_slice_uint8_t__s
{
  FStar_Pervasives_Native_option__size_t_tags tag;
  K___COSE_Format_vercdl_any_pretty_Pulse_Lib_Slice_slice_uint8_t v;
}
FStar_Pervasives_Native_option___COSE_Format_vercdl_any_pretty___Pulse_Lib_Slice_slice_uint8_t_;

FStar_Pervasives_Native_option___COSE_Format_vercdl_any_pretty___Pulse_Lib_Slice_slice_uint8_t_
COSE_Format_validate_and_parse_any(Pulse_Lib_Slice_slice__uint8_t s);

bool COSE_Format_validate_values(cbor_det_t c);

typedef COSE_Format_vercdl_any_pretty COSE_Format_vercdl_values_pretty;

bool COSE_Format_uu___is_Mkvercdl_values_pretty0(COSE_Format_vercdl_any_pretty projectee);

/**
Parser for vercdl_values
*/
COSE_Format_vercdl_any_pretty COSE_Format_parse_values(cbor_det_t c);

/**
Serializer for vercdl_values
*/
size_t
COSE_Format_serialize_values(
  COSE_Format_vercdl_any_pretty c,
  Pulse_Lib_Slice_slice__uint8_t out
);

typedef struct K___COSE_Format_vercdl_values_pretty_Pulse_Lib_Slice_slice_uint8_t_s
{
  COSE_Format_vercdl_any_pretty fst;
  Pulse_Lib_Slice_slice__uint8_t snd;
}
K___COSE_Format_vercdl_values_pretty_Pulse_Lib_Slice_slice_uint8_t;

typedef struct
FStar_Pervasives_Native_option___COSE_Format_vercdl_values_pretty___Pulse_Lib_Slice_slice_uint8_t__s
{
  FStar_Pervasives_Native_option__size_t_tags tag;
  K___COSE_Format_vercdl_values_pretty_Pulse_Lib_Slice_slice_uint8_t v;
}
FStar_Pervasives_Native_option___COSE_Format_vercdl_values_pretty___Pulse_Lib_Slice_slice_uint8_t_;

FStar_Pervasives_Native_option___COSE_Format_vercdl_values_pretty___Pulse_Lib_Slice_slice_uint8_t_
COSE_Format_validate_and_parse_values(Pulse_Lib_Slice_slice__uint8_t s);

bool COSE_Format_aux_env25_validate_1(cbor_det_array_iterator_t *pi);

typedef COSE_Format_vercdl_label_pretty COSE_Format_aux_env25_type_1_pretty;

bool
COSE_Format_uu___is_Mkaux_env25_type_1_pretty0(COSE_Format_vercdl_label_pretty projectee);

/**
Parser for aux_env25_type_1
*/
COSE_Format_vercdl_label_pretty COSE_Format_aux_env25_parse_1(cbor_det_array_iterator_t c);

/**
Serializer for aux_env25_type_1
*/
bool
COSE_Format_aux_env25_serialize_1(
  COSE_Format_vercdl_label_pretty c,
  Pulse_Lib_Slice_slice__uint8_t out,
  uint64_t *out_count,
  size_t *out_size
);

extern bool (*COSE_Format_aux_env25_validate_2)(cbor_det_t x0);

typedef COSE_Format_vercdl_label_pretty COSE_Format_aux_env25_type_2_pretty;

bool
COSE_Format_uu___is_Mkaux_env25_type_2_pretty0(COSE_Format_vercdl_label_pretty projectee);

/**
Parser for aux_env25_type_2
*/
COSE_Format_vercdl_label_pretty COSE_Format_aux_env25_parse_2(cbor_det_t c);

/**
Serializer for aux_env25_type_2
*/
size_t
COSE_Format_aux_env25_serialize_2(
  COSE_Format_vercdl_label_pretty c,
  Pulse_Lib_Slice_slice__uint8_t out
);

typedef struct K___COSE_Format_aux_env25_type_2_pretty_Pulse_Lib_Slice_slice_uint8_t_s
{
  COSE_Format_vercdl_label_pretty fst;
  Pulse_Lib_Slice_slice__uint8_t snd;
}
K___COSE_Format_aux_env25_type_2_pretty_Pulse_Lib_Slice_slice_uint8_t;

typedef struct
FStar_Pervasives_Native_option___COSE_Format_aux_env25_type_2_pretty___Pulse_Lib_Slice_slice_uint8_t__s
{
  FStar_Pervasives_Native_option__size_t_tags tag;
  K___COSE_Format_aux_env25_type_2_pretty_Pulse_Lib_Slice_slice_uint8_t v;
}
FStar_Pervasives_Native_option___COSE_Format_aux_env25_type_2_pretty___Pulse_Lib_Slice_slice_uint8_t_;

FStar_Pervasives_Native_option___COSE_Format_aux_env25_type_2_pretty___Pulse_Lib_Slice_slice_uint8_t_
COSE_Format_validate_and_aux_env25_parse_2(Pulse_Lib_Slice_slice__uint8_t s);

bool COSE_Format_aux_env25_validate_3(cbor_det_t c);

extern bool (*COSE_Format_aux_env25_validate_4)(cbor_det_t x0);

typedef COSE_Format_vercdl_values_pretty COSE_Format_aux_env25_type_4_pretty;

bool
COSE_Format_uu___is_Mkaux_env25_type_4_pretty0(COSE_Format_vercdl_values_pretty projectee);

/**
Parser for aux_env25_type_4
*/
COSE_Format_vercdl_values_pretty COSE_Format_aux_env25_parse_4(cbor_det_t c);

/**
Serializer for aux_env25_type_4
*/
size_t
COSE_Format_aux_env25_serialize_4(
  COSE_Format_vercdl_values_pretty c,
  Pulse_Lib_Slice_slice__uint8_t out
);

typedef struct K___COSE_Format_aux_env25_type_4_pretty_Pulse_Lib_Slice_slice_uint8_t_s
{
  COSE_Format_vercdl_values_pretty fst;
  Pulse_Lib_Slice_slice__uint8_t snd;
}
K___COSE_Format_aux_env25_type_4_pretty_Pulse_Lib_Slice_slice_uint8_t;

typedef struct
FStar_Pervasives_Native_option___COSE_Format_aux_env25_type_4_pretty___Pulse_Lib_Slice_slice_uint8_t__s
{
  FStar_Pervasives_Native_option__size_t_tags tag;
  K___COSE_Format_aux_env25_type_4_pretty_Pulse_Lib_Slice_slice_uint8_t v;
}
FStar_Pervasives_Native_option___COSE_Format_aux_env25_type_4_pretty___Pulse_Lib_Slice_slice_uint8_t_;

FStar_Pervasives_Native_option___COSE_Format_aux_env25_type_4_pretty___Pulse_Lib_Slice_slice_uint8_t_
COSE_Format_validate_and_aux_env25_parse_4(Pulse_Lib_Slice_slice__uint8_t s);

bool COSE_Format_validate_header_map(cbor_det_t c);

typedef struct
FStar_Pervasives_Native_option__FStar_Pervasives_either_COSE_Format_vercdl_int_pretty_COSE_Format_vercdl_tstr_pretty_s
{
  FStar_Pervasives_Native_option__size_t_tags tag;
  COSE_Format_vercdl_label v;
}
FStar_Pervasives_Native_option__FStar_Pervasives_either_COSE_Format_vercdl_int_pretty_COSE_Format_vercdl_tstr_pretty;

typedef struct Pulse_Lib_Slice_slice__COSE_Format_aux_env25_type_1_pretty_s
{
  COSE_Format_vercdl_label_pretty *elt;
  size_t len;
}
Pulse_Lib_Slice_slice__COSE_Format_aux_env25_type_1_pretty;

typedef struct
CDDL_Pulse_Parse_ArrayGroup_array_iterator_t__CBOR_Pulse_API_Det_Type_cbor_det_array_iterator_t_COSE_Format_aux_env25_type_1_pretty_s
{
  cbor_det_array_iterator_t cddl_array_iterator_contents;
  bool (*cddl_array_iterator_impl_validate)(cbor_det_array_iterator_t *x0);
  COSE_Format_vercdl_label_pretty
  (*cddl_array_iterator_impl_parse)(cbor_det_array_iterator_t x0);
}
CDDL_Pulse_Parse_ArrayGroup_array_iterator_t__CBOR_Pulse_API_Det_Type_cbor_det_array_iterator_t_COSE_Format_aux_env25_type_1_pretty;

typedef struct
FStar_Pervasives_either__CDDL_Pulse_Types_slice_COSE_Format_aux_env25_type_1_pretty_CDDL_Pulse_Parse_ArrayGroup_array_iterator_t_CBOR_Pulse_API_Det_Type_cbor_det_array_iterator_t_COSE_Format_aux_env25_type_1_pretty_s
{
  COSE_Format_vercdl_int_tags tag;
  union {
    Pulse_Lib_Slice_slice__COSE_Format_aux_env25_type_1_pretty case_Inl;
    CDDL_Pulse_Parse_ArrayGroup_array_iterator_t__CBOR_Pulse_API_Det_Type_cbor_det_array_iterator_t_COSE_Format_aux_env25_type_1_pretty
    case_Inr;
  }
  ;
}
FStar_Pervasives_either__CDDL_Pulse_Types_slice_COSE_Format_aux_env25_type_1_pretty_CDDL_Pulse_Parse_ArrayGroup_array_iterator_t_CBOR_Pulse_API_Det_Type_cbor_det_array_iterator_t_COSE_Format_aux_env25_type_1_pretty;

typedef struct
FStar_Pervasives_Native_option__FStar_Pervasives_either_CDDL_Pulse_Types_slice_COSE_Format_aux_env25_type_1_pretty_CDDL_Pulse_Parse_ArrayGroup_array_iterator_t_CBOR_Pulse_API_Det_Type_cbor_det_array_iterator_t_COSE_Format_aux_env25_type_1_pretty_s
{
  FStar_Pervasives_Native_option__size_t_tags tag;
  FStar_Pervasives_either__CDDL_Pulse_Types_slice_COSE_Format_aux_env25_type_1_pretty_CDDL_Pulse_Parse_ArrayGroup_array_iterator_t_CBOR_Pulse_API_Det_Type_cbor_det_array_iterator_t_COSE_Format_aux_env25_type_1_pretty
  v;
}
FStar_Pervasives_Native_option__FStar_Pervasives_either_CDDL_Pulse_Types_slice_COSE_Format_aux_env25_type_1_pretty_CDDL_Pulse_Parse_ArrayGroup_array_iterator_t_CBOR_Pulse_API_Det_Type_cbor_det_array_iterator_t_COSE_Format_aux_env25_type_1_pretty;

typedef struct
FStar_Pervasives_either__COSE_Format_vercdl_tstr_pretty_COSE_Format_vercdl_int_pretty_s
{
  COSE_Format_vercdl_int_tags tag;
  union {
    COSE_Format_vercdl_bstr case_Inl;
    COSE_Format_vercdl_int_pretty case_Inr;
  }
  ;
}
FStar_Pervasives_either__COSE_Format_vercdl_tstr_pretty_COSE_Format_vercdl_int_pretty;

typedef struct
FStar_Pervasives_Native_option__FStar_Pervasives_either_COSE_Format_vercdl_tstr_pretty_COSE_Format_vercdl_int_pretty_s
{
  FStar_Pervasives_Native_option__size_t_tags tag;
  FStar_Pervasives_either__COSE_Format_vercdl_tstr_pretty_COSE_Format_vercdl_int_pretty v;
}
FStar_Pervasives_Native_option__FStar_Pervasives_either_COSE_Format_vercdl_tstr_pretty_COSE_Format_vercdl_int_pretty;

typedef struct FStar_Pervasives_Native_option__COSE_Format_vercdl_bstr_pretty_s
{
  FStar_Pervasives_Native_option__size_t_tags tag;
  COSE_Format_vercdl_bstr_pretty v;
}
FStar_Pervasives_Native_option__COSE_Format_vercdl_bstr_pretty;

typedef struct FStar_Pervasives_Native_option__COSE_Format_vercdl_separsenomatch_pretty_s
{
  FStar_Pervasives_Native_option__size_t_tags tag;
  COSE_Format_vercdl_separsenomatch_pretty v;
}
FStar_Pervasives_Native_option__COSE_Format_vercdl_separsenomatch_pretty;

typedef struct
K___COSE_Format_vercdl_bstr_pretty_FStar_Pervasives_Native_option_COSE_Format_vercdl_separsenomatch_pretty_s
{
  COSE_Format_vercdl_bstr fst;
  FStar_Pervasives_Native_option__COSE_Format_vercdl_separsenomatch_pretty snd;
}
K___COSE_Format_vercdl_bstr_pretty_FStar_Pervasives_Native_option_COSE_Format_vercdl_separsenomatch_pretty;

typedef struct
K___FStar_Pervasives_Native_option_COSE_Format_vercdl_separsenomatch_pretty_FStar_Pervasives_Native_option_COSE_Format_vercdl_separsenomatch_pretty_s
{
  FStar_Pervasives_Native_option__COSE_Format_vercdl_separsenomatch_pretty fst;
  FStar_Pervasives_Native_option__COSE_Format_vercdl_separsenomatch_pretty snd;
}
K___FStar_Pervasives_Native_option_COSE_Format_vercdl_separsenomatch_pretty_FStar_Pervasives_Native_option_COSE_Format_vercdl_separsenomatch_pretty;

typedef struct
FStar_Pervasives_either___COSE_Format_vercdl_bstr_pretty___FStar_Pervasives_Native_option_COSE_Format_vercdl_separsenomatch_pretty___FStar_Pervasives_Native_option_COSE_Format_vercdl_separsenomatch_pretty___FStar_Pervasives_Native_option_COSE_Format_vercdl_separsenomatch_pretty__s
{
  COSE_Format_vercdl_int_tags tag;
  union {
    K___COSE_Format_vercdl_bstr_pretty_FStar_Pervasives_Native_option_COSE_Format_vercdl_separsenomatch_pretty
    case_Inl;
    K___FStar_Pervasives_Native_option_COSE_Format_vercdl_separsenomatch_pretty_FStar_Pervasives_Native_option_COSE_Format_vercdl_separsenomatch_pretty
    case_Inr;
  }
  ;
}
FStar_Pervasives_either___COSE_Format_vercdl_bstr_pretty___FStar_Pervasives_Native_option_COSE_Format_vercdl_separsenomatch_pretty___FStar_Pervasives_Native_option_COSE_Format_vercdl_separsenomatch_pretty___FStar_Pervasives_Native_option_COSE_Format_vercdl_separsenomatch_pretty_;

typedef struct
FStar_Pervasives_either___COSE_Format_vercdl_bstr_pretty___FStar_Pervasives_Native_option_COSE_Format_vercdl_separsenomatch_pretty__FStar_Pervasives_either__COSE_Format_vercdl_bstr_pretty___FStar_Pervasives_Native_option_COSE_Format_vercdl_separsenomatch_pretty___FStar_Pervasives_Native_option_COSE_Format_vercdl_separsenomatch_pretty___FStar_Pervasives_Native_option_COSE_Format_vercdl_separsenomatch_pretty__s
{
  COSE_Format_vercdl_int_tags tag;
  union {
    K___COSE_Format_vercdl_bstr_pretty_FStar_Pervasives_Native_option_COSE_Format_vercdl_separsenomatch_pretty
    case_Inl;
    FStar_Pervasives_either___COSE_Format_vercdl_bstr_pretty___FStar_Pervasives_Native_option_COSE_Format_vercdl_separsenomatch_pretty___FStar_Pervasives_Native_option_COSE_Format_vercdl_separsenomatch_pretty___FStar_Pervasives_Native_option_COSE_Format_vercdl_separsenomatch_pretty_
    case_Inr;
  }
  ;
}
FStar_Pervasives_either___COSE_Format_vercdl_bstr_pretty___FStar_Pervasives_Native_option_COSE_Format_vercdl_separsenomatch_pretty__FStar_Pervasives_either__COSE_Format_vercdl_bstr_pretty___FStar_Pervasives_Native_option_COSE_Format_vercdl_separsenomatch_pretty___FStar_Pervasives_Native_option_COSE_Format_vercdl_separsenomatch_pretty___FStar_Pervasives_Native_option_COSE_Format_vercdl_separsenomatch_pretty_;

typedef struct K___COSE_Format_aux_env25_type_2_pretty_COSE_Format_aux_env25_type_4_pretty_s
{
  COSE_Format_vercdl_label_pretty fst;
  COSE_Format_vercdl_values_pretty snd;
}
K___COSE_Format_aux_env25_type_2_pretty_COSE_Format_aux_env25_type_4_pretty;

typedef struct
Pulse_Lib_Slice_slice___COSE_Format_aux_env25_type_2_pretty___COSE_Format_aux_env25_type_4_pretty__s
{
  K___COSE_Format_aux_env25_type_2_pretty_COSE_Format_aux_env25_type_4_pretty *elt;
  size_t len;
}
Pulse_Lib_Slice_slice___COSE_Format_aux_env25_type_2_pretty___COSE_Format_aux_env25_type_4_pretty_;

typedef struct
CDDL_Pulse_Parse_MapGroup_map_iterator_t__CBOR_Pulse_API_Det_Type_cbor_det_t_CBOR_Pulse_API_Det_Type_cbor_det_map_iterator_t_COSE_Format_aux_env25_type_2_pretty_COSE_Format_aux_env25_type_4_pretty_s
{
  cbor_det_map_iterator_t cddl_map_iterator_contents;
  bool (*cddl_map_iterator_impl_validate1)(cbor_det_t x0);
  COSE_Format_vercdl_label_pretty (*cddl_map_iterator_impl_parse1)(cbor_det_t x0);
  bool (*cddl_map_iterator_impl_validate_ex)(cbor_det_t x0);
  bool (*cddl_map_iterator_impl_validate2)(cbor_det_t x0);
  COSE_Format_vercdl_values_pretty (*cddl_map_iterator_impl_parse2)(cbor_det_t x0);
}
CDDL_Pulse_Parse_MapGroup_map_iterator_t__CBOR_Pulse_API_Det_Type_cbor_det_t_CBOR_Pulse_API_Det_Type_cbor_det_map_iterator_t_COSE_Format_aux_env25_type_2_pretty_COSE_Format_aux_env25_type_4_pretty;

typedef struct
FStar_Pervasives_either__CDDL_Pulse_Types_slice__COSE_Format_aux_env25_type_2_pretty___COSE_Format_aux_env25_type_4_pretty__CDDL_Pulse_Parse_MapGroup_map_iterator_t_CBOR_Pulse_API_Det_Type_cbor_det_t_CBOR_Pulse_API_Det_Type_cbor_det_map_iterator_t_COSE_Format_aux_env25_type_2_pretty_COSE_Format_aux_env25_type_4_pretty_s
{
  COSE_Format_vercdl_int_tags tag;
  union {
    Pulse_Lib_Slice_slice___COSE_Format_aux_env25_type_2_pretty___COSE_Format_aux_env25_type_4_pretty_
    case_Inl;
    CDDL_Pulse_Parse_MapGroup_map_iterator_t__CBOR_Pulse_API_Det_Type_cbor_det_t_CBOR_Pulse_API_Det_Type_cbor_det_map_iterator_t_COSE_Format_aux_env25_type_2_pretty_COSE_Format_aux_env25_type_4_pretty
    case_Inr;
  }
  ;
}
FStar_Pervasives_either__CDDL_Pulse_Types_slice__COSE_Format_aux_env25_type_2_pretty___COSE_Format_aux_env25_type_4_pretty__CDDL_Pulse_Parse_MapGroup_map_iterator_t_CBOR_Pulse_API_Det_Type_cbor_det_t_CBOR_Pulse_API_Det_Type_cbor_det_map_iterator_t_COSE_Format_aux_env25_type_2_pretty_COSE_Format_aux_env25_type_4_pretty;

typedef struct COSE_Format_vercdl_header_map_pretty_s
{
  FStar_Pervasives_Native_option__FStar_Pervasives_either_COSE_Format_vercdl_int_pretty_COSE_Format_vercdl_tstr_pretty
  intkey1;
  FStar_Pervasives_Native_option__FStar_Pervasives_either_CDDL_Pulse_Types_slice_COSE_Format_aux_env25_type_1_pretty_CDDL_Pulse_Parse_ArrayGroup_array_iterator_t_CBOR_Pulse_API_Det_Type_cbor_det_array_iterator_t_COSE_Format_aux_env25_type_1_pretty
  intkey2;
  FStar_Pervasives_Native_option__FStar_Pervasives_either_COSE_Format_vercdl_tstr_pretty_COSE_Format_vercdl_int_pretty
  intkey3;
  FStar_Pervasives_Native_option__COSE_Format_vercdl_bstr_pretty intkey4;
  FStar_Pervasives_either___COSE_Format_vercdl_bstr_pretty___FStar_Pervasives_Native_option_COSE_Format_vercdl_separsenomatch_pretty__FStar_Pervasives_either__COSE_Format_vercdl_bstr_pretty___FStar_Pervasives_Native_option_COSE_Format_vercdl_separsenomatch_pretty___FStar_Pervasives_Native_option_COSE_Format_vercdl_separsenomatch_pretty___FStar_Pervasives_Native_option_COSE_Format_vercdl_separsenomatch_pretty_
  _x0;
  FStar_Pervasives_either__CDDL_Pulse_Types_slice__COSE_Format_aux_env25_type_2_pretty___COSE_Format_aux_env25_type_4_pretty__CDDL_Pulse_Parse_MapGroup_map_iterator_t_CBOR_Pulse_API_Det_Type_cbor_det_t_CBOR_Pulse_API_Det_Type_cbor_det_map_iterator_t_COSE_Format_aux_env25_type_2_pretty_COSE_Format_aux_env25_type_4_pretty
  _x1;
}
COSE_Format_vercdl_header_map_pretty;

bool
COSE_Format_uu___is_Mkvercdl_header_map_pretty0(
  COSE_Format_vercdl_header_map_pretty projectee
);

/**
Parser for vercdl_header_map
*/
COSE_Format_vercdl_header_map_pretty COSE_Format_parse_header_map(cbor_det_t c);

/**
Serializer for vercdl_header_map
*/
size_t
COSE_Format_serialize_header_map(
  COSE_Format_vercdl_header_map_pretty c,
  Pulse_Lib_Slice_slice__uint8_t out
);

typedef struct K___COSE_Format_vercdl_header_map_pretty_Pulse_Lib_Slice_slice_uint8_t_s
{
  COSE_Format_vercdl_header_map_pretty fst;
  Pulse_Lib_Slice_slice__uint8_t snd;
}
K___COSE_Format_vercdl_header_map_pretty_Pulse_Lib_Slice_slice_uint8_t;

typedef struct
FStar_Pervasives_Native_option___COSE_Format_vercdl_header_map_pretty___Pulse_Lib_Slice_slice_uint8_t__s
{
  FStar_Pervasives_Native_option__size_t_tags tag;
  K___COSE_Format_vercdl_header_map_pretty_Pulse_Lib_Slice_slice_uint8_t v;
}
FStar_Pervasives_Native_option___COSE_Format_vercdl_header_map_pretty___Pulse_Lib_Slice_slice_uint8_t_;

FStar_Pervasives_Native_option___COSE_Format_vercdl_header_map_pretty___Pulse_Lib_Slice_slice_uint8_t_
COSE_Format_validate_and_parse_header_map(Pulse_Lib_Slice_slice__uint8_t s);

bool
COSE_Format_is_empty_iterate_array_aux_env25_type_1(
  CDDL_Pulse_Parse_ArrayGroup_array_iterator_t__CBOR_Pulse_API_Det_Type_cbor_det_array_iterator_t_COSE_Format_aux_env25_type_1_pretty
  i
);

COSE_Format_vercdl_label_pretty
COSE_Format_next_iterate_array_aux_env25_type_1(
  CDDL_Pulse_Parse_ArrayGroup_array_iterator_t__CBOR_Pulse_API_Det_Type_cbor_det_array_iterator_t_COSE_Format_aux_env25_type_1_pretty
  *pi
);

bool
COSE_Format_is_empty_iterate_map_aux_env25_type_2_and_aux_env25_type_4(
  CDDL_Pulse_Parse_MapGroup_map_iterator_t__CBOR_Pulse_API_Det_Type_cbor_det_t_CBOR_Pulse_API_Det_Type_cbor_det_map_iterator_t_COSE_Format_aux_env25_type_2_pretty_COSE_Format_aux_env25_type_4_pretty
  i
);

K___COSE_Format_aux_env25_type_2_pretty_COSE_Format_aux_env25_type_4_pretty
COSE_Format_next_iterate_map_aux_env25_type_2_and_aux_env25_type_4(
  CDDL_Pulse_Parse_MapGroup_map_iterator_t__CBOR_Pulse_API_Det_Type_cbor_det_t_CBOR_Pulse_API_Det_Type_cbor_det_map_iterator_t_COSE_Format_aux_env25_type_2_pretty_COSE_Format_aux_env25_type_4_pretty
  *pi
);

bool COSE_Format_validate_empty_or_serialized_map(cbor_det_t c);

typedef enum {
  COSE_Format_Mkvercdl_empty_or_serialized_map_pretty0,
  COSE_Format_Mkvercdl_empty_or_serialized_map_pretty1
}
COSE_Format_vercdl_empty_or_serialized_map_pretty_tags;

typedef struct COSE_Format_vercdl_empty_or_serialized_map_pretty_s
{
  COSE_Format_vercdl_empty_or_serialized_map_pretty_tags tag;
  union {
    COSE_Format_vercdl_header_map_pretty case_Mkvercdl_empty_or_serialized_map_pretty0;
    Pulse_Lib_Slice_slice__uint8_t case_Mkvercdl_empty_or_serialized_map_pretty1;
  }
  ;
}
COSE_Format_vercdl_empty_or_serialized_map_pretty;

bool
COSE_Format_uu___is_Mkvercdl_empty_or_serialized_map_pretty0(
  COSE_Format_vercdl_empty_or_serialized_map_pretty projectee
);

bool
COSE_Format_uu___is_Mkvercdl_empty_or_serialized_map_pretty1(
  COSE_Format_vercdl_empty_or_serialized_map_pretty projectee
);

/**
Parser for vercdl_empty_or_serialized_map
*/
COSE_Format_vercdl_empty_or_serialized_map_pretty
COSE_Format_parse_empty_or_serialized_map(cbor_det_t c);

/**
Serializer for vercdl_empty_or_serialized_map
*/
size_t
COSE_Format_serialize_empty_or_serialized_map(
  COSE_Format_vercdl_empty_or_serialized_map_pretty c,
  Pulse_Lib_Slice_slice__uint8_t out
);

typedef struct
K___COSE_Format_vercdl_empty_or_serialized_map_pretty_Pulse_Lib_Slice_slice_uint8_t_s
{
  COSE_Format_vercdl_empty_or_serialized_map_pretty fst;
  Pulse_Lib_Slice_slice__uint8_t snd;
}
K___COSE_Format_vercdl_empty_or_serialized_map_pretty_Pulse_Lib_Slice_slice_uint8_t;

typedef struct
FStar_Pervasives_Native_option___COSE_Format_vercdl_empty_or_serialized_map_pretty___Pulse_Lib_Slice_slice_uint8_t__s
{
  FStar_Pervasives_Native_option__size_t_tags tag;
  K___COSE_Format_vercdl_empty_or_serialized_map_pretty_Pulse_Lib_Slice_slice_uint8_t v;
}
FStar_Pervasives_Native_option___COSE_Format_vercdl_empty_or_serialized_map_pretty___Pulse_Lib_Slice_slice_uint8_t_;

FStar_Pervasives_Native_option___COSE_Format_vercdl_empty_or_serialized_map_pretty___Pulse_Lib_Slice_slice_uint8_t_
COSE_Format_validate_and_parse_empty_or_serialized_map(Pulse_Lib_Slice_slice__uint8_t s);

bool COSE_Format_validate_COSE_Signature(cbor_det_t c);

typedef struct COSE_Format_vercdl_COSE_Signature_pretty_s
{
  COSE_Format_vercdl_empty_or_serialized_map_pretty protected;
  COSE_Format_vercdl_header_map_pretty unprotected;
  COSE_Format_vercdl_bstr signature;
}
COSE_Format_vercdl_COSE_Signature_pretty;

bool
COSE_Format_uu___is_Mkvercdl_COSE_Signature_pretty0(
  COSE_Format_vercdl_COSE_Signature_pretty projectee
);

/**
Parser for vercdl_COSE_Signature
*/
COSE_Format_vercdl_COSE_Signature_pretty COSE_Format_parse_COSE_Signature(cbor_det_t c);

/**
Serializer for vercdl_COSE_Signature
*/
size_t
COSE_Format_serialize_COSE_Signature(
  COSE_Format_vercdl_COSE_Signature_pretty c,
  Pulse_Lib_Slice_slice__uint8_t out
);

typedef struct K___COSE_Format_vercdl_COSE_Signature_pretty_Pulse_Lib_Slice_slice_uint8_t_s
{
  COSE_Format_vercdl_COSE_Signature_pretty fst;
  Pulse_Lib_Slice_slice__uint8_t snd;
}
K___COSE_Format_vercdl_COSE_Signature_pretty_Pulse_Lib_Slice_slice_uint8_t;

typedef struct
FStar_Pervasives_Native_option___COSE_Format_vercdl_COSE_Signature_pretty___Pulse_Lib_Slice_slice_uint8_t__s
{
  FStar_Pervasives_Native_option__size_t_tags tag;
  K___COSE_Format_vercdl_COSE_Signature_pretty_Pulse_Lib_Slice_slice_uint8_t v;
}
FStar_Pervasives_Native_option___COSE_Format_vercdl_COSE_Signature_pretty___Pulse_Lib_Slice_slice_uint8_t_;

FStar_Pervasives_Native_option___COSE_Format_vercdl_COSE_Signature_pretty___Pulse_Lib_Slice_slice_uint8_t_
COSE_Format_validate_and_parse_COSE_Signature(Pulse_Lib_Slice_slice__uint8_t s);

bool COSE_Format_aux_env29_validate_1(cbor_det_array_iterator_t *pi);

typedef COSE_Format_vercdl_COSE_Signature_pretty COSE_Format_aux_env29_type_1_pretty;

bool
COSE_Format_uu___is_Mkaux_env29_type_1_pretty0(
  COSE_Format_vercdl_COSE_Signature_pretty projectee
);

/**
Parser for aux_env29_type_1
*/
COSE_Format_vercdl_COSE_Signature_pretty
COSE_Format_aux_env29_parse_1(cbor_det_array_iterator_t c);

/**
Serializer for aux_env29_type_1
*/
bool
COSE_Format_aux_env29_serialize_1(
  COSE_Format_vercdl_COSE_Signature_pretty c,
  Pulse_Lib_Slice_slice__uint8_t out,
  uint64_t *out_count,
  size_t *out_size
);

bool COSE_Format_validate_COSE_Sign(cbor_det_t c);

typedef struct
FStar_Pervasives_either__COSE_Format_vercdl_bstr_pretty_COSE_Format_vercdl_nil_pretty_s
{
  COSE_Format_vercdl_int_tags tag;
  union {
    COSE_Format_vercdl_bstr case_Inl;
    COSE_Format_vercdl_nil_pretty case_Inr;
  }
  ;
}
FStar_Pervasives_either__COSE_Format_vercdl_bstr_pretty_COSE_Format_vercdl_nil_pretty;

typedef struct Pulse_Lib_Slice_slice__COSE_Format_aux_env29_type_1_pretty_s
{
  COSE_Format_vercdl_COSE_Signature_pretty *elt;
  size_t len;
}
Pulse_Lib_Slice_slice__COSE_Format_aux_env29_type_1_pretty;

typedef struct
CDDL_Pulse_Parse_ArrayGroup_array_iterator_t__CBOR_Pulse_API_Det_Type_cbor_det_array_iterator_t_COSE_Format_aux_env29_type_1_pretty_s
{
  cbor_det_array_iterator_t cddl_array_iterator_contents;
  bool (*cddl_array_iterator_impl_validate)(cbor_det_array_iterator_t *x0);
  COSE_Format_vercdl_COSE_Signature_pretty
  (*cddl_array_iterator_impl_parse)(cbor_det_array_iterator_t x0);
}
CDDL_Pulse_Parse_ArrayGroup_array_iterator_t__CBOR_Pulse_API_Det_Type_cbor_det_array_iterator_t_COSE_Format_aux_env29_type_1_pretty;

typedef struct
FStar_Pervasives_either__CDDL_Pulse_Types_slice_COSE_Format_aux_env29_type_1_pretty_CDDL_Pulse_Parse_ArrayGroup_array_iterator_t_CBOR_Pulse_API_Det_Type_cbor_det_array_iterator_t_COSE_Format_aux_env29_type_1_pretty_s
{
  COSE_Format_vercdl_int_tags tag;
  union {
    Pulse_Lib_Slice_slice__COSE_Format_aux_env29_type_1_pretty case_Inl;
    CDDL_Pulse_Parse_ArrayGroup_array_iterator_t__CBOR_Pulse_API_Det_Type_cbor_det_array_iterator_t_COSE_Format_aux_env29_type_1_pretty
    case_Inr;
  }
  ;
}
FStar_Pervasives_either__CDDL_Pulse_Types_slice_COSE_Format_aux_env29_type_1_pretty_CDDL_Pulse_Parse_ArrayGroup_array_iterator_t_CBOR_Pulse_API_Det_Type_cbor_det_array_iterator_t_COSE_Format_aux_env29_type_1_pretty;

typedef struct COSE_Format_vercdl_COSE_Sign_pretty_s
{
  COSE_Format_vercdl_empty_or_serialized_map_pretty protected;
  COSE_Format_vercdl_header_map_pretty unprotected;
  FStar_Pervasives_either__COSE_Format_vercdl_bstr_pretty_COSE_Format_vercdl_nil_pretty
  payload;
  FStar_Pervasives_either__CDDL_Pulse_Types_slice_COSE_Format_aux_env29_type_1_pretty_CDDL_Pulse_Parse_ArrayGroup_array_iterator_t_CBOR_Pulse_API_Det_Type_cbor_det_array_iterator_t_COSE_Format_aux_env29_type_1_pretty
  signatures;
}
COSE_Format_vercdl_COSE_Sign_pretty;

bool
COSE_Format_uu___is_Mkvercdl_COSE_Sign_pretty0(
  COSE_Format_vercdl_COSE_Sign_pretty projectee
);

/**
Parser for vercdl_COSE_Sign
*/
COSE_Format_vercdl_COSE_Sign_pretty COSE_Format_parse_COSE_Sign(cbor_det_t c);

/**
Serializer for vercdl_COSE_Sign
*/
size_t
COSE_Format_serialize_COSE_Sign(
  COSE_Format_vercdl_COSE_Sign_pretty c,
  Pulse_Lib_Slice_slice__uint8_t out
);

typedef struct K___COSE_Format_vercdl_COSE_Sign_pretty_Pulse_Lib_Slice_slice_uint8_t_s
{
  COSE_Format_vercdl_COSE_Sign_pretty fst;
  Pulse_Lib_Slice_slice__uint8_t snd;
}
K___COSE_Format_vercdl_COSE_Sign_pretty_Pulse_Lib_Slice_slice_uint8_t;

typedef struct
FStar_Pervasives_Native_option___COSE_Format_vercdl_COSE_Sign_pretty___Pulse_Lib_Slice_slice_uint8_t__s
{
  FStar_Pervasives_Native_option__size_t_tags tag;
  K___COSE_Format_vercdl_COSE_Sign_pretty_Pulse_Lib_Slice_slice_uint8_t v;
}
FStar_Pervasives_Native_option___COSE_Format_vercdl_COSE_Sign_pretty___Pulse_Lib_Slice_slice_uint8_t_;

FStar_Pervasives_Native_option___COSE_Format_vercdl_COSE_Sign_pretty___Pulse_Lib_Slice_slice_uint8_t_
COSE_Format_validate_and_parse_COSE_Sign(Pulse_Lib_Slice_slice__uint8_t s);

bool
COSE_Format_is_empty_iterate_array_aux_env29_type_1(
  CDDL_Pulse_Parse_ArrayGroup_array_iterator_t__CBOR_Pulse_API_Det_Type_cbor_det_array_iterator_t_COSE_Format_aux_env29_type_1_pretty
  i
);

COSE_Format_vercdl_COSE_Signature_pretty
COSE_Format_next_iterate_array_aux_env29_type_1(
  CDDL_Pulse_Parse_ArrayGroup_array_iterator_t__CBOR_Pulse_API_Det_Type_cbor_det_array_iterator_t_COSE_Format_aux_env29_type_1_pretty
  *pi
);

bool COSE_Format_validate_COSE_Sign_Tagged(cbor_det_t c);

typedef COSE_Format_vercdl_COSE_Sign_pretty COSE_Format_vercdl_COSE_Sign_Tagged_pretty;

bool
COSE_Format_uu___is_Mkvercdl_COSE_Sign_Tagged_pretty0(
  COSE_Format_vercdl_COSE_Sign_pretty projectee
);

/**
Parser for vercdl_COSE_Sign_Tagged
*/
COSE_Format_vercdl_COSE_Sign_pretty COSE_Format_parse_COSE_Sign_Tagged(cbor_det_t c);

/**
Serializer for vercdl_COSE_Sign_Tagged
*/
size_t
COSE_Format_serialize_COSE_Sign_Tagged(
  COSE_Format_vercdl_COSE_Sign_pretty c,
  Pulse_Lib_Slice_slice__uint8_t out
);

typedef struct K___COSE_Format_vercdl_COSE_Sign_Tagged_pretty_Pulse_Lib_Slice_slice_uint8_t_s
{
  COSE_Format_vercdl_COSE_Sign_pretty fst;
  Pulse_Lib_Slice_slice__uint8_t snd;
}
K___COSE_Format_vercdl_COSE_Sign_Tagged_pretty_Pulse_Lib_Slice_slice_uint8_t;

typedef struct
FStar_Pervasives_Native_option___COSE_Format_vercdl_COSE_Sign_Tagged_pretty___Pulse_Lib_Slice_slice_uint8_t__s
{
  FStar_Pervasives_Native_option__size_t_tags tag;
  K___COSE_Format_vercdl_COSE_Sign_Tagged_pretty_Pulse_Lib_Slice_slice_uint8_t v;
}
FStar_Pervasives_Native_option___COSE_Format_vercdl_COSE_Sign_Tagged_pretty___Pulse_Lib_Slice_slice_uint8_t_;

FStar_Pervasives_Native_option___COSE_Format_vercdl_COSE_Sign_Tagged_pretty___Pulse_Lib_Slice_slice_uint8_t_
COSE_Format_validate_and_parse_COSE_Sign_Tagged(Pulse_Lib_Slice_slice__uint8_t s);

bool COSE_Format_validate_COSE_Sign1(cbor_det_t c);

typedef struct COSE_Format_vercdl_COSE_Sign1_pretty_s
{
  COSE_Format_vercdl_empty_or_serialized_map_pretty protected;
  COSE_Format_vercdl_header_map_pretty unprotected;
  FStar_Pervasives_either__COSE_Format_vercdl_bstr_pretty_COSE_Format_vercdl_nil_pretty
  payload;
  COSE_Format_vercdl_bstr signature;
}
COSE_Format_vercdl_COSE_Sign1_pretty;

bool
COSE_Format_uu___is_Mkvercdl_COSE_Sign1_pretty0(
  COSE_Format_vercdl_COSE_Sign1_pretty projectee
);

/**
Parser for vercdl_COSE_Sign1
*/
COSE_Format_vercdl_COSE_Sign1_pretty COSE_Format_parse_COSE_Sign1(cbor_det_t c);

/**
Serializer for vercdl_COSE_Sign1
*/
size_t
COSE_Format_serialize_COSE_Sign1(
  COSE_Format_vercdl_COSE_Sign1_pretty c,
  Pulse_Lib_Slice_slice__uint8_t out
);

typedef struct K___COSE_Format_vercdl_COSE_Sign1_pretty_Pulse_Lib_Slice_slice_uint8_t_s
{
  COSE_Format_vercdl_COSE_Sign1_pretty fst;
  Pulse_Lib_Slice_slice__uint8_t snd;
}
K___COSE_Format_vercdl_COSE_Sign1_pretty_Pulse_Lib_Slice_slice_uint8_t;

typedef struct
FStar_Pervasives_Native_option___COSE_Format_vercdl_COSE_Sign1_pretty___Pulse_Lib_Slice_slice_uint8_t__s
{
  FStar_Pervasives_Native_option__size_t_tags tag;
  K___COSE_Format_vercdl_COSE_Sign1_pretty_Pulse_Lib_Slice_slice_uint8_t v;
}
FStar_Pervasives_Native_option___COSE_Format_vercdl_COSE_Sign1_pretty___Pulse_Lib_Slice_slice_uint8_t_;

FStar_Pervasives_Native_option___COSE_Format_vercdl_COSE_Sign1_pretty___Pulse_Lib_Slice_slice_uint8_t_
COSE_Format_validate_and_parse_COSE_Sign1(Pulse_Lib_Slice_slice__uint8_t s);

bool COSE_Format_validate_COSE_Untagged_Message(cbor_det_t c);

typedef enum {
  COSE_Format_Mkvercdl_COSE_Untagged_Message_pretty0,
  COSE_Format_Mkvercdl_COSE_Untagged_Message_pretty1
}
COSE_Format_vercdl_COSE_Untagged_Message_pretty_tags;

typedef struct COSE_Format_vercdl_COSE_Untagged_Message_pretty_s
{
  COSE_Format_vercdl_COSE_Untagged_Message_pretty_tags tag;
  union {
    COSE_Format_vercdl_COSE_Sign_pretty case_Mkvercdl_COSE_Untagged_Message_pretty0;
    COSE_Format_vercdl_COSE_Sign1_pretty case_Mkvercdl_COSE_Untagged_Message_pretty1;
  }
  ;
}
COSE_Format_vercdl_COSE_Untagged_Message_pretty;

bool
COSE_Format_uu___is_Mkvercdl_COSE_Untagged_Message_pretty0(
  COSE_Format_vercdl_COSE_Untagged_Message_pretty projectee
);

bool
COSE_Format_uu___is_Mkvercdl_COSE_Untagged_Message_pretty1(
  COSE_Format_vercdl_COSE_Untagged_Message_pretty projectee
);

/**
Parser for vercdl_COSE_Untagged_Message
*/
COSE_Format_vercdl_COSE_Untagged_Message_pretty
COSE_Format_parse_COSE_Untagged_Message(cbor_det_t c);

/**
Serializer for vercdl_COSE_Untagged_Message
*/
size_t
COSE_Format_serialize_COSE_Untagged_Message(
  COSE_Format_vercdl_COSE_Untagged_Message_pretty c,
  Pulse_Lib_Slice_slice__uint8_t out
);

typedef struct
K___COSE_Format_vercdl_COSE_Untagged_Message_pretty_Pulse_Lib_Slice_slice_uint8_t_s
{
  COSE_Format_vercdl_COSE_Untagged_Message_pretty fst;
  Pulse_Lib_Slice_slice__uint8_t snd;
}
K___COSE_Format_vercdl_COSE_Untagged_Message_pretty_Pulse_Lib_Slice_slice_uint8_t;

typedef struct
FStar_Pervasives_Native_option___COSE_Format_vercdl_COSE_Untagged_Message_pretty___Pulse_Lib_Slice_slice_uint8_t__s
{
  FStar_Pervasives_Native_option__size_t_tags tag;
  K___COSE_Format_vercdl_COSE_Untagged_Message_pretty_Pulse_Lib_Slice_slice_uint8_t v;
}
FStar_Pervasives_Native_option___COSE_Format_vercdl_COSE_Untagged_Message_pretty___Pulse_Lib_Slice_slice_uint8_t_;

FStar_Pervasives_Native_option___COSE_Format_vercdl_COSE_Untagged_Message_pretty___Pulse_Lib_Slice_slice_uint8_t_
COSE_Format_validate_and_parse_COSE_Untagged_Message(Pulse_Lib_Slice_slice__uint8_t s);

bool COSE_Format_validate_COSE_Sign1_Tagged(cbor_det_t c);

typedef COSE_Format_vercdl_COSE_Sign1_pretty COSE_Format_vercdl_COSE_Sign1_Tagged_pretty;

bool
COSE_Format_uu___is_Mkvercdl_COSE_Sign1_Tagged_pretty0(
  COSE_Format_vercdl_COSE_Sign1_pretty projectee
);

/**
Parser for vercdl_COSE_Sign1_Tagged
*/
COSE_Format_vercdl_COSE_Sign1_pretty COSE_Format_parse_COSE_Sign1_Tagged(cbor_det_t c);

/**
Serializer for vercdl_COSE_Sign1_Tagged
*/
size_t
COSE_Format_serialize_COSE_Sign1_Tagged(
  COSE_Format_vercdl_COSE_Sign1_pretty c,
  Pulse_Lib_Slice_slice__uint8_t out
);

typedef struct
K___COSE_Format_vercdl_COSE_Sign1_Tagged_pretty_Pulse_Lib_Slice_slice_uint8_t_s
{
  COSE_Format_vercdl_COSE_Sign1_pretty fst;
  Pulse_Lib_Slice_slice__uint8_t snd;
}
K___COSE_Format_vercdl_COSE_Sign1_Tagged_pretty_Pulse_Lib_Slice_slice_uint8_t;

typedef struct
FStar_Pervasives_Native_option___COSE_Format_vercdl_COSE_Sign1_Tagged_pretty___Pulse_Lib_Slice_slice_uint8_t__s
{
  FStar_Pervasives_Native_option__size_t_tags tag;
  K___COSE_Format_vercdl_COSE_Sign1_Tagged_pretty_Pulse_Lib_Slice_slice_uint8_t v;
}
FStar_Pervasives_Native_option___COSE_Format_vercdl_COSE_Sign1_Tagged_pretty___Pulse_Lib_Slice_slice_uint8_t_;

FStar_Pervasives_Native_option___COSE_Format_vercdl_COSE_Sign1_Tagged_pretty___Pulse_Lib_Slice_slice_uint8_t_
COSE_Format_validate_and_parse_COSE_Sign1_Tagged(Pulse_Lib_Slice_slice__uint8_t s);

bool COSE_Format_validate_COSE_Tagged_Message(cbor_det_t c);

typedef enum {
  COSE_Format_Mkvercdl_COSE_Tagged_Message_pretty0,
  COSE_Format_Mkvercdl_COSE_Tagged_Message_pretty1
}
COSE_Format_vercdl_COSE_Tagged_Message_pretty_tags;

typedef struct COSE_Format_vercdl_COSE_Tagged_Message_pretty_s
{
  COSE_Format_vercdl_COSE_Tagged_Message_pretty_tags tag;
  union {
    COSE_Format_vercdl_COSE_Sign_pretty case_Mkvercdl_COSE_Tagged_Message_pretty0;
    COSE_Format_vercdl_COSE_Sign1_pretty case_Mkvercdl_COSE_Tagged_Message_pretty1;
  }
  ;
}
COSE_Format_vercdl_COSE_Tagged_Message_pretty;

bool
COSE_Format_uu___is_Mkvercdl_COSE_Tagged_Message_pretty0(
  COSE_Format_vercdl_COSE_Tagged_Message_pretty projectee
);

bool
COSE_Format_uu___is_Mkvercdl_COSE_Tagged_Message_pretty1(
  COSE_Format_vercdl_COSE_Tagged_Message_pretty projectee
);

/**
Parser for vercdl_COSE_Tagged_Message
*/
COSE_Format_vercdl_COSE_Tagged_Message_pretty
COSE_Format_parse_COSE_Tagged_Message(cbor_det_t c);

/**
Serializer for vercdl_COSE_Tagged_Message
*/
size_t
COSE_Format_serialize_COSE_Tagged_Message(
  COSE_Format_vercdl_COSE_Tagged_Message_pretty c,
  Pulse_Lib_Slice_slice__uint8_t out
);

typedef struct
K___COSE_Format_vercdl_COSE_Tagged_Message_pretty_Pulse_Lib_Slice_slice_uint8_t_s
{
  COSE_Format_vercdl_COSE_Tagged_Message_pretty fst;
  Pulse_Lib_Slice_slice__uint8_t snd;
}
K___COSE_Format_vercdl_COSE_Tagged_Message_pretty_Pulse_Lib_Slice_slice_uint8_t;

typedef struct
FStar_Pervasives_Native_option___COSE_Format_vercdl_COSE_Tagged_Message_pretty___Pulse_Lib_Slice_slice_uint8_t__s
{
  FStar_Pervasives_Native_option__size_t_tags tag;
  K___COSE_Format_vercdl_COSE_Tagged_Message_pretty_Pulse_Lib_Slice_slice_uint8_t v;
}
FStar_Pervasives_Native_option___COSE_Format_vercdl_COSE_Tagged_Message_pretty___Pulse_Lib_Slice_slice_uint8_t_;

FStar_Pervasives_Native_option___COSE_Format_vercdl_COSE_Tagged_Message_pretty___Pulse_Lib_Slice_slice_uint8_t_
COSE_Format_validate_and_parse_COSE_Tagged_Message(Pulse_Lib_Slice_slice__uint8_t s);

bool COSE_Format_validate_COSE_Messages(cbor_det_t c);

typedef enum {
  COSE_Format_Mkvercdl_COSE_Messages_pretty0,
  COSE_Format_Mkvercdl_COSE_Messages_pretty1
}
COSE_Format_vercdl_COSE_Messages_pretty_tags;

typedef struct COSE_Format_vercdl_COSE_Messages_pretty_s
{
  COSE_Format_vercdl_COSE_Messages_pretty_tags tag;
  union {
    COSE_Format_vercdl_COSE_Untagged_Message_pretty case_Mkvercdl_COSE_Messages_pretty0;
    COSE_Format_vercdl_COSE_Tagged_Message_pretty case_Mkvercdl_COSE_Messages_pretty1;
  }
  ;
}
COSE_Format_vercdl_COSE_Messages_pretty;

bool
COSE_Format_uu___is_Mkvercdl_COSE_Messages_pretty0(
  COSE_Format_vercdl_COSE_Messages_pretty projectee
);

bool
COSE_Format_uu___is_Mkvercdl_COSE_Messages_pretty1(
  COSE_Format_vercdl_COSE_Messages_pretty projectee
);

/**
Parser for vercdl_COSE_Messages
*/
COSE_Format_vercdl_COSE_Messages_pretty COSE_Format_parse_COSE_Messages(cbor_det_t c);

/**
Serializer for vercdl_COSE_Messages
*/
size_t
COSE_Format_serialize_COSE_Messages(
  COSE_Format_vercdl_COSE_Messages_pretty c,
  Pulse_Lib_Slice_slice__uint8_t out
);

typedef struct K___COSE_Format_vercdl_COSE_Messages_pretty_Pulse_Lib_Slice_slice_uint8_t_s
{
  COSE_Format_vercdl_COSE_Messages_pretty fst;
  Pulse_Lib_Slice_slice__uint8_t snd;
}
K___COSE_Format_vercdl_COSE_Messages_pretty_Pulse_Lib_Slice_slice_uint8_t;

typedef struct
FStar_Pervasives_Native_option___COSE_Format_vercdl_COSE_Messages_pretty___Pulse_Lib_Slice_slice_uint8_t__s
{
  FStar_Pervasives_Native_option__size_t_tags tag;
  K___COSE_Format_vercdl_COSE_Messages_pretty_Pulse_Lib_Slice_slice_uint8_t v;
}
FStar_Pervasives_Native_option___COSE_Format_vercdl_COSE_Messages_pretty___Pulse_Lib_Slice_slice_uint8_t_;

FStar_Pervasives_Native_option___COSE_Format_vercdl_COSE_Messages_pretty___Pulse_Lib_Slice_slice_uint8_t_
COSE_Format_validate_and_parse_COSE_Messages(Pulse_Lib_Slice_slice__uint8_t s);

bool COSE_Format_validate_Sig_structure(cbor_det_t c);

typedef struct K___COSE_Format_vercdl_bstr_pretty_COSE_Format_vercdl_bstr_pretty_s
{
  COSE_Format_vercdl_bstr fst;
  COSE_Format_vercdl_bstr snd;
}
K___COSE_Format_vercdl_bstr_pretty_COSE_Format_vercdl_bstr_pretty;

typedef struct
K___COSE_Format_vercdl_empty_or_serialized_map_pretty__COSE_Format_vercdl_bstr_pretty___COSE_Format_vercdl_bstr_pretty__s
{
  COSE_Format_vercdl_empty_or_serialized_map_pretty fst;
  K___COSE_Format_vercdl_bstr_pretty_COSE_Format_vercdl_bstr_pretty snd;
}
K___COSE_Format_vercdl_empty_or_serialized_map_pretty__COSE_Format_vercdl_bstr_pretty___COSE_Format_vercdl_bstr_pretty_;

typedef struct
FStar_Pervasives_either___COSE_Format_vercdl_empty_or_serialized_map_pretty____COSE_Format_vercdl_bstr_pretty___COSE_Format_vercdl_bstr_pretty____COSE_Format_vercdl_bstr_pretty___COSE_Format_vercdl_bstr_pretty__s
{
  COSE_Format_vercdl_int_tags tag;
  union {
    K___COSE_Format_vercdl_empty_or_serialized_map_pretty__COSE_Format_vercdl_bstr_pretty___COSE_Format_vercdl_bstr_pretty_
    case_Inl;
    K___COSE_Format_vercdl_bstr_pretty_COSE_Format_vercdl_bstr_pretty case_Inr;
  }
  ;
}
FStar_Pervasives_either___COSE_Format_vercdl_empty_or_serialized_map_pretty____COSE_Format_vercdl_bstr_pretty___COSE_Format_vercdl_bstr_pretty____COSE_Format_vercdl_bstr_pretty___COSE_Format_vercdl_bstr_pretty_;

typedef struct COSE_Format_vercdl_Sig_structure_pretty_s
{
  COSE_Format_vercdl_int_tags context;
  COSE_Format_vercdl_empty_or_serialized_map_pretty body_protected;
  FStar_Pervasives_either___COSE_Format_vercdl_empty_or_serialized_map_pretty____COSE_Format_vercdl_bstr_pretty___COSE_Format_vercdl_bstr_pretty____COSE_Format_vercdl_bstr_pretty___COSE_Format_vercdl_bstr_pretty_
  _x0;
}
COSE_Format_vercdl_Sig_structure_pretty;

bool
COSE_Format_uu___is_Mkvercdl_Sig_structure_pretty0(
  COSE_Format_vercdl_Sig_structure_pretty projectee
);

/**
Parser for vercdl_Sig_structure
*/
COSE_Format_vercdl_Sig_structure_pretty COSE_Format_parse_Sig_structure(cbor_det_t c);

/**
Serializer for vercdl_Sig_structure
*/
size_t
COSE_Format_serialize_Sig_structure(
  COSE_Format_vercdl_Sig_structure_pretty c,
  Pulse_Lib_Slice_slice__uint8_t out
);

typedef struct K___COSE_Format_vercdl_Sig_structure_pretty_Pulse_Lib_Slice_slice_uint8_t_s
{
  COSE_Format_vercdl_Sig_structure_pretty fst;
  Pulse_Lib_Slice_slice__uint8_t snd;
}
K___COSE_Format_vercdl_Sig_structure_pretty_Pulse_Lib_Slice_slice_uint8_t;

typedef struct
FStar_Pervasives_Native_option___COSE_Format_vercdl_Sig_structure_pretty___Pulse_Lib_Slice_slice_uint8_t__s
{
  FStar_Pervasives_Native_option__size_t_tags tag;
  K___COSE_Format_vercdl_Sig_structure_pretty_Pulse_Lib_Slice_slice_uint8_t v;
}
FStar_Pervasives_Native_option___COSE_Format_vercdl_Sig_structure_pretty___Pulse_Lib_Slice_slice_uint8_t_;

FStar_Pervasives_Native_option___COSE_Format_vercdl_Sig_structure_pretty___Pulse_Lib_Slice_slice_uint8_t_
COSE_Format_validate_and_parse_Sig_structure(Pulse_Lib_Slice_slice__uint8_t s);

bool COSE_Format_validate_Internal_Types(cbor_det_t c);

typedef COSE_Format_vercdl_Sig_structure_pretty COSE_Format_vercdl_Internal_Types_pretty;

bool
COSE_Format_uu___is_Mkvercdl_Internal_Types_pretty0(
  COSE_Format_vercdl_Sig_structure_pretty projectee
);

/**
Parser for vercdl_Internal_Types
*/
COSE_Format_vercdl_Sig_structure_pretty COSE_Format_parse_Internal_Types(cbor_det_t c);

/**
Serializer for vercdl_Internal_Types
*/
size_t
COSE_Format_serialize_Internal_Types(
  COSE_Format_vercdl_Sig_structure_pretty c,
  Pulse_Lib_Slice_slice__uint8_t out
);

typedef struct K___COSE_Format_vercdl_Internal_Types_pretty_Pulse_Lib_Slice_slice_uint8_t_s
{
  COSE_Format_vercdl_Sig_structure_pretty fst;
  Pulse_Lib_Slice_slice__uint8_t snd;
}
K___COSE_Format_vercdl_Internal_Types_pretty_Pulse_Lib_Slice_slice_uint8_t;

typedef struct
FStar_Pervasives_Native_option___COSE_Format_vercdl_Internal_Types_pretty___Pulse_Lib_Slice_slice_uint8_t__s
{
  FStar_Pervasives_Native_option__size_t_tags tag;
  K___COSE_Format_vercdl_Internal_Types_pretty_Pulse_Lib_Slice_slice_uint8_t v;
}
FStar_Pervasives_Native_option___COSE_Format_vercdl_Internal_Types_pretty___Pulse_Lib_Slice_slice_uint8_t_;

FStar_Pervasives_Native_option___COSE_Format_vercdl_Internal_Types_pretty___Pulse_Lib_Slice_slice_uint8_t_
COSE_Format_validate_and_parse_Internal_Types(Pulse_Lib_Slice_slice__uint8_t s);

bool COSE_Format_validate_start(cbor_det_t c);

typedef enum { COSE_Format_Mkvercdl_start_pretty0, COSE_Format_Mkvercdl_start_pretty1 }
COSE_Format_vercdl_start_pretty_tags;

typedef struct COSE_Format_vercdl_start_pretty_s
{
  COSE_Format_vercdl_start_pretty_tags tag;
  union {
    COSE_Format_vercdl_COSE_Messages_pretty case_Mkvercdl_start_pretty0;
    COSE_Format_vercdl_Sig_structure_pretty case_Mkvercdl_start_pretty1;
  }
  ;
}
COSE_Format_vercdl_start_pretty;

bool COSE_Format_uu___is_Mkvercdl_start_pretty0(COSE_Format_vercdl_start_pretty projectee);

bool COSE_Format_uu___is_Mkvercdl_start_pretty1(COSE_Format_vercdl_start_pretty projectee);

/**
Parser for vercdl_start
*/
COSE_Format_vercdl_start_pretty COSE_Format_parse_start(cbor_det_t c);

/**
Serializer for vercdl_start
*/
size_t
COSE_Format_serialize_start(
  COSE_Format_vercdl_start_pretty c,
  Pulse_Lib_Slice_slice__uint8_t out
);

typedef struct K___COSE_Format_vercdl_start_pretty_Pulse_Lib_Slice_slice_uint8_t_s
{
  COSE_Format_vercdl_start_pretty fst;
  Pulse_Lib_Slice_slice__uint8_t snd;
}
K___COSE_Format_vercdl_start_pretty_Pulse_Lib_Slice_slice_uint8_t;

typedef struct
FStar_Pervasives_Native_option___COSE_Format_vercdl_start_pretty___Pulse_Lib_Slice_slice_uint8_t__s
{
  FStar_Pervasives_Native_option__size_t_tags tag;
  K___COSE_Format_vercdl_start_pretty_Pulse_Lib_Slice_slice_uint8_t v;
}
FStar_Pervasives_Native_option___COSE_Format_vercdl_start_pretty___Pulse_Lib_Slice_slice_uint8_t_;

FStar_Pervasives_Native_option___COSE_Format_vercdl_start_pretty___Pulse_Lib_Slice_slice_uint8_t_
COSE_Format_validate_and_parse_start(Pulse_Lib_Slice_slice__uint8_t s);

bool COSE_Format_aux_env39_validate_1(cbor_det_t c);

bool COSE_Format_validate_COSE_Key_OKP(cbor_det_t c);

typedef struct COSE_Format_vercdl_COSE_Key_OKP_pretty_s
{
  COSE_Format_vercdl_label intkeyneg1;
  FStar_Pervasives_Native_option__COSE_Format_vercdl_bstr_pretty intkeyneg2;
  FStar_Pervasives_Native_option__COSE_Format_vercdl_bstr_pretty intkeyneg4;
  FStar_Pervasives_either__CDDL_Pulse_Types_slice__COSE_Format_aux_env25_type_2_pretty___COSE_Format_aux_env25_type_4_pretty__CDDL_Pulse_Parse_MapGroup_map_iterator_t_CBOR_Pulse_API_Det_Type_cbor_det_t_CBOR_Pulse_API_Det_Type_cbor_det_map_iterator_t_COSE_Format_aux_env25_type_2_pretty_COSE_Format_aux_env25_type_4_pretty
  _x0;
}
COSE_Format_vercdl_COSE_Key_OKP_pretty;

bool
COSE_Format_uu___is_Mkvercdl_COSE_Key_OKP_pretty0(
  COSE_Format_vercdl_COSE_Key_OKP_pretty projectee
);

/**
Parser for vercdl_COSE_Key_OKP
*/
COSE_Format_vercdl_COSE_Key_OKP_pretty COSE_Format_parse_COSE_Key_OKP(cbor_det_t c);

/**
Serializer for vercdl_COSE_Key_OKP
*/
size_t
COSE_Format_serialize_COSE_Key_OKP(
  COSE_Format_vercdl_COSE_Key_OKP_pretty c,
  Pulse_Lib_Slice_slice__uint8_t out
);

typedef struct K___COSE_Format_vercdl_COSE_Key_OKP_pretty_Pulse_Lib_Slice_slice_uint8_t_s
{
  COSE_Format_vercdl_COSE_Key_OKP_pretty fst;
  Pulse_Lib_Slice_slice__uint8_t snd;
}
K___COSE_Format_vercdl_COSE_Key_OKP_pretty_Pulse_Lib_Slice_slice_uint8_t;

typedef struct
FStar_Pervasives_Native_option___COSE_Format_vercdl_COSE_Key_OKP_pretty___Pulse_Lib_Slice_slice_uint8_t__s
{
  FStar_Pervasives_Native_option__size_t_tags tag;
  K___COSE_Format_vercdl_COSE_Key_OKP_pretty_Pulse_Lib_Slice_slice_uint8_t v;
}
FStar_Pervasives_Native_option___COSE_Format_vercdl_COSE_Key_OKP_pretty___Pulse_Lib_Slice_slice_uint8_t_;

FStar_Pervasives_Native_option___COSE_Format_vercdl_COSE_Key_OKP_pretty___Pulse_Lib_Slice_slice_uint8_t_
COSE_Format_validate_and_parse_COSE_Key_OKP(Pulse_Lib_Slice_slice__uint8_t s);

bool COSE_Format_validate_COSE_Key(cbor_det_t c);

typedef COSE_Format_vercdl_COSE_Key_OKP_pretty COSE_Format_vercdl_COSE_Key_pretty;

bool
COSE_Format_uu___is_Mkvercdl_COSE_Key_pretty0(
  COSE_Format_vercdl_COSE_Key_OKP_pretty projectee
);

/**
Parser for vercdl_COSE_Key
*/
COSE_Format_vercdl_COSE_Key_OKP_pretty COSE_Format_parse_COSE_Key(cbor_det_t c);

/**
Serializer for vercdl_COSE_Key
*/
size_t
COSE_Format_serialize_COSE_Key(
  COSE_Format_vercdl_COSE_Key_OKP_pretty c,
  Pulse_Lib_Slice_slice__uint8_t out
);

typedef struct K___COSE_Format_vercdl_COSE_Key_pretty_Pulse_Lib_Slice_slice_uint8_t_s
{
  COSE_Format_vercdl_COSE_Key_OKP_pretty fst;
  Pulse_Lib_Slice_slice__uint8_t snd;
}
K___COSE_Format_vercdl_COSE_Key_pretty_Pulse_Lib_Slice_slice_uint8_t;

typedef struct
FStar_Pervasives_Native_option___COSE_Format_vercdl_COSE_Key_pretty___Pulse_Lib_Slice_slice_uint8_t__s
{
  FStar_Pervasives_Native_option__size_t_tags tag;
  K___COSE_Format_vercdl_COSE_Key_pretty_Pulse_Lib_Slice_slice_uint8_t v;
}
FStar_Pervasives_Native_option___COSE_Format_vercdl_COSE_Key_pretty___Pulse_Lib_Slice_slice_uint8_t_;

FStar_Pervasives_Native_option___COSE_Format_vercdl_COSE_Key_pretty___Pulse_Lib_Slice_slice_uint8_t_
COSE_Format_validate_and_parse_COSE_Key(Pulse_Lib_Slice_slice__uint8_t s);

bool COSE_Format_validate_eb64url(cbor_det_t c);

typedef COSE_Format_vercdl_any_pretty COSE_Format_vercdl_eb64url_pretty;

bool COSE_Format_uu___is_Mkvercdl_eb64url_pretty0(COSE_Format_vercdl_any_pretty projectee);

/**
Parser for vercdl_eb64url
*/
COSE_Format_vercdl_any_pretty COSE_Format_parse_eb64url(cbor_det_t c);

/**
Serializer for vercdl_eb64url
*/
size_t
COSE_Format_serialize_eb64url(
  COSE_Format_vercdl_any_pretty c,
  Pulse_Lib_Slice_slice__uint8_t out
);

typedef struct K___COSE_Format_vercdl_eb64url_pretty_Pulse_Lib_Slice_slice_uint8_t_s
{
  COSE_Format_vercdl_any_pretty fst;
  Pulse_Lib_Slice_slice__uint8_t snd;
}
K___COSE_Format_vercdl_eb64url_pretty_Pulse_Lib_Slice_slice_uint8_t;

typedef struct
FStar_Pervasives_Native_option___COSE_Format_vercdl_eb64url_pretty___Pulse_Lib_Slice_slice_uint8_t__s
{
  FStar_Pervasives_Native_option__size_t_tags tag;
  K___COSE_Format_vercdl_eb64url_pretty_Pulse_Lib_Slice_slice_uint8_t v;
}
FStar_Pervasives_Native_option___COSE_Format_vercdl_eb64url_pretty___Pulse_Lib_Slice_slice_uint8_t_;

FStar_Pervasives_Native_option___COSE_Format_vercdl_eb64url_pretty___Pulse_Lib_Slice_slice_uint8_t_
COSE_Format_validate_and_parse_eb64url(Pulse_Lib_Slice_slice__uint8_t s);

bool COSE_Format_validate_eb64legacy(cbor_det_t c);

typedef COSE_Format_vercdl_any_pretty COSE_Format_vercdl_eb64legacy_pretty;

bool
COSE_Format_uu___is_Mkvercdl_eb64legacy_pretty0(COSE_Format_vercdl_any_pretty projectee);

/**
Parser for vercdl_eb64legacy
*/
COSE_Format_vercdl_any_pretty COSE_Format_parse_eb64legacy(cbor_det_t c);

/**
Serializer for vercdl_eb64legacy
*/
size_t
COSE_Format_serialize_eb64legacy(
  COSE_Format_vercdl_any_pretty c,
  Pulse_Lib_Slice_slice__uint8_t out
);

typedef struct K___COSE_Format_vercdl_eb64legacy_pretty_Pulse_Lib_Slice_slice_uint8_t_s
{
  COSE_Format_vercdl_any_pretty fst;
  Pulse_Lib_Slice_slice__uint8_t snd;
}
K___COSE_Format_vercdl_eb64legacy_pretty_Pulse_Lib_Slice_slice_uint8_t;

typedef struct
FStar_Pervasives_Native_option___COSE_Format_vercdl_eb64legacy_pretty___Pulse_Lib_Slice_slice_uint8_t__s
{
  FStar_Pervasives_Native_option__size_t_tags tag;
  K___COSE_Format_vercdl_eb64legacy_pretty_Pulse_Lib_Slice_slice_uint8_t v;
}
FStar_Pervasives_Native_option___COSE_Format_vercdl_eb64legacy_pretty___Pulse_Lib_Slice_slice_uint8_t_;

FStar_Pervasives_Native_option___COSE_Format_vercdl_eb64legacy_pretty___Pulse_Lib_Slice_slice_uint8_t_
COSE_Format_validate_and_parse_eb64legacy(Pulse_Lib_Slice_slice__uint8_t s);

bool COSE_Format_validate_eb16(cbor_det_t c);

typedef COSE_Format_vercdl_any_pretty COSE_Format_vercdl_eb16_pretty;

bool COSE_Format_uu___is_Mkvercdl_eb16_pretty0(COSE_Format_vercdl_any_pretty projectee);

/**
Parser for vercdl_eb16
*/
COSE_Format_vercdl_any_pretty COSE_Format_parse_eb16(cbor_det_t c);

/**
Serializer for vercdl_eb16
*/
size_t
COSE_Format_serialize_eb16(
  COSE_Format_vercdl_any_pretty c,
  Pulse_Lib_Slice_slice__uint8_t out
);

typedef struct K___COSE_Format_vercdl_eb16_pretty_Pulse_Lib_Slice_slice_uint8_t_s
{
  COSE_Format_vercdl_any_pretty fst;
  Pulse_Lib_Slice_slice__uint8_t snd;
}
K___COSE_Format_vercdl_eb16_pretty_Pulse_Lib_Slice_slice_uint8_t;

typedef struct
FStar_Pervasives_Native_option___COSE_Format_vercdl_eb16_pretty___Pulse_Lib_Slice_slice_uint8_t__s
{
  FStar_Pervasives_Native_option__size_t_tags tag;
  K___COSE_Format_vercdl_eb16_pretty_Pulse_Lib_Slice_slice_uint8_t v;
}
FStar_Pervasives_Native_option___COSE_Format_vercdl_eb16_pretty___Pulse_Lib_Slice_slice_uint8_t_;

FStar_Pervasives_Native_option___COSE_Format_vercdl_eb16_pretty___Pulse_Lib_Slice_slice_uint8_t_
COSE_Format_validate_and_parse_eb16(Pulse_Lib_Slice_slice__uint8_t s);

bool COSE_Format_validate_cborany(cbor_det_t c);

typedef COSE_Format_vercdl_any_pretty COSE_Format_vercdl_cborany_pretty;

bool COSE_Format_uu___is_Mkvercdl_cborany_pretty0(COSE_Format_vercdl_any_pretty projectee);

/**
Parser for vercdl_cborany
*/
COSE_Format_vercdl_any_pretty COSE_Format_parse_cborany(cbor_det_t c);

/**
Serializer for vercdl_cborany
*/
size_t
COSE_Format_serialize_cborany(
  COSE_Format_vercdl_any_pretty c,
  Pulse_Lib_Slice_slice__uint8_t out
);

typedef struct K___COSE_Format_vercdl_cborany_pretty_Pulse_Lib_Slice_slice_uint8_t_s
{
  COSE_Format_vercdl_any_pretty fst;
  Pulse_Lib_Slice_slice__uint8_t snd;
}
K___COSE_Format_vercdl_cborany_pretty_Pulse_Lib_Slice_slice_uint8_t;

typedef struct
FStar_Pervasives_Native_option___COSE_Format_vercdl_cborany_pretty___Pulse_Lib_Slice_slice_uint8_t__s
{
  FStar_Pervasives_Native_option__size_t_tags tag;
  K___COSE_Format_vercdl_cborany_pretty_Pulse_Lib_Slice_slice_uint8_t v;
}
FStar_Pervasives_Native_option___COSE_Format_vercdl_cborany_pretty___Pulse_Lib_Slice_slice_uint8_t_;

FStar_Pervasives_Native_option___COSE_Format_vercdl_cborany_pretty___Pulse_Lib_Slice_slice_uint8_t_
COSE_Format_validate_and_parse_cborany(Pulse_Lib_Slice_slice__uint8_t s);


#define __COSE_Format_H_DEFINED
#endif
